### PR TITLE
Fix error with PODS_LIGHT and components

### PR DESCRIPTION
**Pull request by JoryHogeveen**
Related: #2301 #3811 #2293

### CODE REVIEW

**Comment by szepeviktor** [comment]
Thank you. It is OK though the Components menu is active and empty.

**Comment by szepeviktor** [comment]
You may close #3811 after merging this one.

**Comment by JoryHogeveen** [comment]
@szepeviktor 
Please check again, found another error + it not checks for `PODS_LIGHT` before creating the admin menus.
Related: https://github.com/pods-framework/pods/issues/2293

**Comment by szepeviktor** [comment]
Looks OK.

**Comment by szepeviktor** [comment]
@sc0ttkclark Do we have something to do here?

**Pull request merged**
