### PR TITLE
update the importer to the newest version

### PR DESCRIPTION
**Pull request by tommiekeeston**
cptui changed the name of their option vars, now are :
cpt_custom_tax_types -> cptui_post_types
cpt_custom_post_types -> cptui_post_types

i've tested the script and its importing correctly i guess, maybe its missing some field but its working.

the function to clean after import doesn't work and need to be checked

### CODE REVIEW

**Comment by NikV** [comment]
I have tested this PR with taxonomies and custom post types with the simple importer and can confirm that so far, it works with the new version. Not sure of the problems with the clean function. Also, what missing field problems did you have @tommiekeeston?

**Comment by sc0ttkclark** [comment]
We need to find a way to make this version dependent on what version CPTUI they are actually running. Currently this code will make older versions of CPTUI no longer work to migrate, so that would require them upgrade CPTUI first before importing into Pods.

@tw2113 Does the new CPTUI remove it's old options? Basically wondering if we could run into any potential issues with CPT / CT that may have been deleted since they upgraded -- and them showing up as the result of our backwards compatibility fix.

**Comment by tw2113** [comment]
Nope, we leave the options alone for the 0.9.x and earlier versions. The user would have to manually delete them to get them removed, or have some sort of data loss occur. Not something we trigger at all ourselves though.

**Comment by sc0ttkclark** [comment]
@tommiekeeston we'll want to check the CPT_VERSION constant here.

```php
if ( defined( 'CPT_VERSION' ) && version_compare( '0.9.0', CPT_VERSION, '<=' ) ) {
    // New options get / update
} else {
    // Old options get / update
}
```

Do two if/else statements, one when migrating, one when cleanup (update).

The only difference for the cleanup is that we want to delete both the old and the new versions of the CPTUI options.

**Comment by sc0ttkclark** [comment]
We also need this PR redone for two branches instead of `master`.

One for Pods 2.x (`2.x` branch)

One for Pods 3.0 (`release/3.0` branch)

**Pull request closed without merging**
