### PR TITLE
Adding WordPress standards RE #2824

### PR DESCRIPTION
**Pull request by NikV**
Please see: https://github.com/pods-framework/pods/pull/2824#issuecomment-90144226

### CODE REVIEW

**Comment by Shelob9** [comment]
Thanks for the update @NikV

**Comment by sc0ttkclark** [comment]
@pglewis heads up on this

**Comment by Ramoonus** [comment]
travis fails on third-party php version requirements

**Comment by sc0ttkclark** [comment]
Needs refresh with latest 3.0, update all `@since unknown` with `@since 2.0.0`

**Pull request closed without merging**
