### PR TITLE
Always convert with UTC timezone

### LINKED ISSUE #5382: UTC time issue on custom pods date time fields
Hi there, 
I have an issue with hours display for custom pods date/time fields. 

My WP should be in UTC+2 (Belgian hour) but if I do so, when adding a date into one of my pods, it actually remove 3 hours to the time added. Let's I write 10 am, after saving it will show 7 am. The only way to have a correct display of the website is to define it at UTC-1, but then the saving time is incorrect... 

In WP general settings, the time stamp under the UTC settings is showing the correct time if I choose UTC+2. Also this issue doesn't seem to affect the time of the post (it's not changing after saving).

Any idea of what can be wrong? Thanks in advance!

Brigitte

---

EDIT BY JORY:

## WordPress Environment

<details>
```
Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.
```
</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

### PR DESCRIPTION
**Pull request by JoryHogeveen**
Fixes #5382, #5402, #5403 and probably more

## Description

Currently after date/time values are stored into the database the date/time field convert them using the WordPress timezone setting (in cases where DateTime is available). This conversion is incorrect since it returns a different value than the user's input.

## ChangeLog
* Always convert database value for date/time fields with UTC timezone to maintain the actual value.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by pglewis** [comment]
Works for me

**Comment by brigbe** [comment]
Works for me too.

**Comment by triclub** [comment]
Thanks, all. We're having this issue in our wordpress instance. Any idea when it will be available in an update?

**Comment by pglewis** [comment]
> Thanks, all. We're having this issue in our wordpress instance. Any idea when it will be available in an update?

This fix is now merged into 2.x and a hotfix release primarily for this issue should go out this week.

**Comment by edellingham** [comment]
I've updated to the latest version and have cleared cache, but I'm still experiencing this issue.  The time always reverts to UTC when making a change to a Date/Time Field.  I tried to use the hotfix referenced here, but the file I guess has been deleted since the official fix was added.

**Comment by JoryHogeveen** [comment]
@edellingham 
Could you test #5418 ?
I've omitted the timezone fully in that PR so it will use the server's timezone.

**Comment by pglewis** [comment]
> I've updated to the latest version and have cleared cache, but I'm still experiencing this issue. The time always reverts to UTC when making a change to a Date/Time Field. I tried to use the hotfix referenced here, but the file I guess has been deleted since the official fix was added.

@edellingham: If you have the time to create a new issue with direct steps to reproduce the problem as minimally as possible it would help a lot.  I was able to recreate it before the hotfix and verified that this PR fixed the issue that I had reproduced locally, so I don't yet know what the circumstances are to reproduce it.  Plus we'd have a clear thread of conversation for the remaining problem, this a closed PR.

**Comment by jeiseman** [comment]
This update causes incorrect behavior (sometimes). It will now (sometimes) assume the stored time is UTC time and then the time gets reset to the current timezone. So, if the time stored is 9:00am, it gets displayed as 5:00am (in the New York timezone). This problem is resolved by reverting to Pods version 2.7.13. The weird thing is that it doesn't always happen. Sometimes when I do $pod->display('time') to display the time field it will work correctly but in a different context it displays the incorrect time. I haven't figured out why it happens in one context but not in others.
Changing the code to the following fixes the problem:
`       // $time = $rpod->display('time');
        $strtime = $rpod->field('time');
        $t = strtotime($strtime);
        $time = date("g:ia", $t);
`

**Comment by JoryHogeveen** [comment]
@jeiseman See #5418 !

**Pull request merged**
