### PR TITLE
is_empty() field method + fix [if] template tags

### PR DESCRIPTION
**Pull request by JoryHogeveen**
Issue: #4227 

- [x] new field method: is_empty()
- implement method in all fields accordingly
  - [x] Number/Currency (required: #4209)
  - [x] Date/Time
  - [x] More @sc0ttkclark 
- [x] use it in the [if] statement checks @sc0ttkclark

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Ready for testing @jimtrue

**Comment by jimtrue** [comment]
Passes all but Currency, Number with 0.00 passes as 'empty' and Date/Time/Time all succeed in empty checks with [if][/if]

**Comment by jimtrue** [comment]
Just to be safe, I revisited those fields in my admin, cleared cache, etc. Everything passes but Currency at 0.00

**Comment by sc0ttkclark** [comment]
Shortcode to reproduce is `[if field="currency_field"]something[/if]`?

**Comment by jimtrue** [comment]
Nope, `[if currency_field]{@currency_field}[else]No Currency[/if]`

**Comment by sc0ttkclark** [comment]
Sorry, our bad, this PR will start working when we merge #4209

**Comment by jimtrue** [comment]
In a Pods Template, I don't believe this will run inside a regular Pods Shortcode.

**Comment by sc0ttkclark** [comment]
Currency begins to extend the Number field, which it'll pick up the `is_empty()` method once that merges.

**Comment by sc0ttkclark** [comment]
@jimtrue try now

**Comment by jimtrue** [comment]
Passed and thanks!

**Pull request merged**
