### PR TITLE
Support webp as default image extension

### PR DESCRIPTION
**Pull request by JoryHogeveen**
## Description

This PR adds the webp extension to the default image extensions for the file field.

## Related GitHub issue(s)

Fixes: https://github.com/pods-framework/pods/issues/6577 (verified)

## PR checklist

- [x] I have tested my own code to confirm it works as I intended.
- [x] My code follows the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] My code follows the [WordPress Inline Documentation Standards](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/).

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
We should technically be supporting any registered audio/ mime type for audio, and video/ mime type for videos, and image/ mime type for images.

See this for the logic we should really be using here. https://github.com/pods-framework/pods/blob/release/2.9/classes/fields/file.php#L1157

That gives full support for whatever WP and other plugins enable for image/video/audio.

The "etc" does a lot of heavy lifting here so we could describe that as " and any others registered with WP"

**Comment by sc0ttkclark** [comment]
Updated PR with the refactor/changes to future-proof our support of the main media types and reduce logic duplication that existed in the handling of it.

@JoryHogeveen If you can put this through a few tests, that'd be helpful -- otherwise I will do that in the next few days before merging.

**Comment by JoryHogeveen** [comment]
`images-any` > webp doesn't show in the available list when selecting files. File filter not correct or WP doesn't include webp by default?

Other than that it seems good. WP indeed adds several other MIME types if the any option is selected.

**Comment by sc0ttkclark** [comment]
Merging and we can sort out whatever edge case there is with images-any later. It all works when I run through the tests on my side so there may be something else going on that we can figure out later.

**Pull request merged**
