### PR TITLE
Clarify what does and doesn't get deleted on reset

### PR DESCRIPTION
**Pull request by NikV**
https://github.com/pods-framework/pods/issues/2778

### CODE REVIEW

**Comment by Shelob9** [comment]
@NikV On this and the 2.x one, can you please redo to move the HTML out of the translation string. I know it was like that when you found it, but might as well improve it while we are in there.

**Comment by NikV** [comment]
Should I remove completely, or just rearrange it?

**Comment by Shelob9** [comment]
Use sprinf() to separate markup from the translation string.

**Comment by NikV** [comment]
Hey @Shelob9, before I fix the 2.0 branch I just added a commit for 3.0, does that look OK?

**Comment by Shelob9** [comment]
@NikV Perfect. Please apply same fix to 2.x

**Pull request merged**
