### PR TITLE
Fix for fatal error when Pods is activated for the whole network.

### PR DESCRIPTION
**Pull request by JoryHogeveen**
Related:

https://github.com/pods-framework/pods/issues/825
https://github.com/pods-framework/pods/issues/2803
https://github.com/pods-framework/pods/issues/3353

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
I'm +1 for this but that was added for some reason that we should definitely do a little more testing on to ensure we're not fixing one bug but re-exposing a previous bug.

**Comment by JoryHogeveen** [comment]
I think this was added because Pods doesn't create any network settings pages so one would guess the pods_init would not be needed there.
But if I'm corrent this makes no sense since if a plugin isn't activated for the whole network then the plugin isn't loaded on the network pages at all.
Please correct me if I'm wrong!

Anyhow, I don't how this patch could create a bug anywhere but I totally agree with testing in more cases.
For what it's worth, this patch didn't create any bugs on my networks! :-)

**Comment by sc0ttkclark** [comment]
I'll just note a few test cases that I seem to recall, when someone is able to (you, one of our other users, or one of our team members) test them, we can merge if we don't encounter any issues.

Prerequisite: Have this patched code in place

* Activating Pods network-wide
* Going to network admin pages (any, including Plugins)
* Upgrading Pods plugin (this one may be tricky, not sure how best to do this until we can verify other issues aren't caused and then push out the code in a release)
* Installing and activating other plugins network-wide

**Comment by sc0ttkclark** [comment]
Oh I remember another case here, if the plugin is activated on the *main site* of the network, but not network-wide, check the network admin pages there too.

**Comment by JoryHogeveen** [comment]
Here is the first commit that introduced the network check:

https://github.com/pods-framework/pods/commit/a55e62f5828036320581f7749823d88eff510af3

It had something to do with content-type caching.
Maybe we can make an other change.

The post_init() is called from pods/includes/general.php on line 1789, maybe this call isn't needed when we're on a network page? If that is so, we could best leave this as is and change that file.

Thoughts?

**Comment by sc0ttkclark** [comment]
I think if we can verify Activation on the main network site (not network-wide), visiting network admin pages works, and visiting network admin pages when Pods is network-activated works -- I'm happy to merge this.

**Comment by JoryHogeveen** [comment]
Please check https://github.com/pods-framework/pods/commit/a55e62f5828036320581f7749823d88eff510af3 first. I'm not sure why this was added since I'm not familiar with content-type caching but I think it will mean more to you :-)

**Comment by JoryHogeveen** [comment]
Hi Scott, did you manage to check https://github.com/pods-framework/pods/commit/a55e62f5828036320581f7749823d88eff510af3 ? Let me know!

**Comment by sc0ttkclark** [comment]
Unfortunately it's been too long to really know, even looking at it now

**Comment by JoryHogeveen** [comment]
Any news on this?

**Comment by sc0ttkclark** [comment]
We just needed more testing to ensure this doesn't break in some situations.

**Comment by JoryHogeveen** [comment]
Ok, for me all testing is done in the last years, I do this change manually after every update of Pods for every multisite I manage for at least 2 years now :-)

No idea what https://github.com/pods-framework/pods/commit/a55e62f5828036320581f7749823d88eff510af3 is supposed to actually fix/change.

**Pull request merged**
