### PR TITLE
composer: switch to phpunit 4.6

### PR DESCRIPTION
**Pull request by Ramoonus**
current version of phpunit is 4.5.2

### CODE REVIEW

**Comment by Ramoonus** [comment]
https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-4.4.md

https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-4.5.md

**Comment by Ramoonus** [comment]
strangely WordPress 3.9-4.1 and HHVM builds work

**Comment by Ramoonus** [comment]
maybe this should be tested with the 2.x branch instead
the build fails mostly on Pods 3 stuff, not PHPUnit things

**Comment by Ramoonus** [comment]
can be upped to  4.6.0 right now

**Comment by Ramoonus** [comment]
i think it`s now ready

**Comment by sc0ttkclark** [comment]
Can you refresh your branch and push? Will merge

**Comment by Ramoonus** [comment]
you want this on?; 
2.x
release/3.0

**Comment by sc0ttkclark** [comment]
Both yeah

**Comment by Ramoonus** [comment]
done:
#2987 
#2988

**Pull request closed without merging**
