### PR TITLE
Link field editor ID,  CSS and wp_editor fix + i18n for JS strings

### PR DESCRIPTION
**Pull request by JoryHogeveen**

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
I18n still needs work on the /ui/fields-mv/_src/ js files otherwise the changes get overwritten on next JS build.

**Comment by JoryHogeveen** [comment]
@sc0ttkclark the "throw" methods, shall I add these aswell?

**Comment by JoryHogeveen** [comment]
@pglewis please check implementation on the .html js templated. I've noticed you use <%- %> to echo variables.

**Comment by JoryHogeveen** [comment]
Closing this one because of conflicts and the invalid JS stuff.

Link PR: https://github.com/pods-framework/pods/pull/3624
JS i18n PR: https://github.com/pods-framework/pods/pull/3619

**Pull request closed without merging**
