### PR TITLE
CSS updates/optimizations for cleditor

### PR DESCRIPTION
**Pull request by nicdford**
Fix for #4631

### CODE REVIEW

**Comment by nicdford** [comment]
Oh this is my bad, I wasn't sure how to handle that with the changes merging in from #4632 where I address that issue as its own commit. Should I address it here and revert that commit?

**Comment by pglewis** [comment]
We'll be wrapping this in another upcoming PR, so this one is good to go

**Comment by pglewis** [comment]
@nicdford: can you give us a good changelog text for this, unless the PR title covers it

**Comment by nicdford** [comment]
# Changelog note
Quality of life visual updates for the CLEditor

**Pull request merged**
