### PR TITLE
Enhance Date/Time fields - Class inheritance & WP defaults + custom options

### LINKED ISSUE #3829: [if] Template Tags do not recognize empty date fields as empty
[if] Template Tags do not recognize empty date fields as empty submitted via Slack by jimtrue

### PR DESCRIPTION
**Pull request by JoryHogeveen**
Issue: #4105 
Related: #2208 , #4107

- [x] Use `datetime` as main class and extend it for `date` and `time` fields.
- [x] Create a converter script for JS formats (no need to have this logic in the form field file)
- [x] Option to use WP Default format in both backend and front end
- [x] Option to create your own format
  - _Be aware that jQuery UI doesn't support all formatting that PHP does!_
- [x] Backwards compat for existing PHP and JS filters
- [x] Optional custom format input for jQueryUI formats
  - Custom JS (field input) format needs to be compatible with `strtotime()` after conversion to PHP date() format.
- [x] Fix #3829
- [x] Tests: functionality + backwards compatibility @jimtrue 
- [x] Convert file indentation to Tabs once PR is ready @JoryHogeveen

**Feedback request:**
- [x] Review option names
- [x] Review help texts
- [x] (Date/Time input only, no format validation possible currently) Maybe add format validation? @sc0ttkclark 
  - Can be done with `strtotime()` or `DateTime::createFromFormat()`
- [x] (Do both) _Maybe only allow custom formats for front-end?_ @jimtrue @sc0ttkclark 
  - Currently the code doesn't work when adding any kind of text or non-date characters because using the datepicker it returns a formatted string instead of a timecode.
- [x] DateTime field: Allow custom input for date/time combined instead of separate? @sc0ttkclark @jimtrue (NOPE)

### CODE REVIEW

**Comment by JoryHogeveen** [comment]
@sc0ttkclark Tests are failing though

**Comment by sc0ttkclark** [comment]
I've merged latest into the branch from 2.7, let's see if tests are passing now or if there are issues to resolve. I can't imagine what would cause any of the stuff to fail here from the changelog, so it might have been something in 2.7 from what i can tell.

**Comment by sc0ttkclark** [comment]
Yeah looks like we do have some issues with testing the date/datetime/time fields. How does this test out when using normally right now? Notice any issues with saving data or getting it from field() or display()?

**Comment by JoryHogeveen** [comment]
Nope, didn't see any errors. I also have no idea what these tests do that are failing..

**Comment by sc0ttkclark** [comment]
They are using the old field options, so it's possible there's a back-compat issue here

**Comment by sc0ttkclark** [comment]
* We need to test this on a site that has Pods 2.6.8 on it and has an existing pod with an existing date field added to it.
* We'll want a shortcode to output the field value on a demo page.
* Then we upgrade Pods to this feature https://github.com/pods-framework/pods/archive/feature/4105-custom-datetime-options.zip
* Without modifying any pods or fields, go to the demo page and then confirm the date is showing up the same as when running Pods 2.6.8

**Comment by JoryHogeveen** [comment]
@jimtrue 
When you have the time, can you do some tests? (See above)

**Comment by jimtrue** [comment]
@JoryHogeveen I'll do my best to get that test done today or tomorrow. It would help to have a list of date formats to test against. I don't do that much with them myself, so we should probably keep a string of them handy to validate against.

**Comment by JoryHogeveen** [comment]
@jimtrue Main thing is the upgrade from the current stable version. Everything should keep working the same.
Second thing is indeed making sure the existing and new options work. Custom strings have limitations but after saving a post Pods will generate an error is the config isn't correct.

**Comment by jimtrue** [comment]
@JoryHogeveen @sc0ttkclark Per the notes above, those tests passed.

Ready to test modifying existing fields and date/time strings

**Comment by jimtrue** [comment]
Those were using default date/time configurations, though

**Comment by jimtrue** [comment]
@JoryHogeveen Instead of the PHP Date & Time Formatting, should we maybe reference them to the WordPress Codex one? https://codex.wordpress.org/Formatting_Date_and_Time (and/or both?)

**Comment by jimtrue** [comment]
"Predefined format" does that mean the format that was initially in the date/time, date or time input field? Some help text on that one would help:

"Predefined format" - Former version of Pods format, please choose WordPress Default or Custom?

**Comment by jimtrue** [comment]
Sorry Predefined would be 'select from a list of available formats' got it. WordPress default would mean it's defined under the General, Settings for the WordPress Installation and Custom would mean it would be defined using the PHP schema from the docs for just this field.

**Comment by jimtrue** [comment]
@JoryHogeveen @sc0ttkclark I think we should set the DEFAULT field format for date, date/time and time on NEW fields to WordPress default. That would ensure the most consistency with what they did the work on.

**Comment by jimtrue** [comment]
Nevermind! @JoryHogeveen already did that ;)

**Comment by jimtrue** [comment]
@JoryHogeveen @sc0ttkclark Everything looks really good from my tests. I tend to test your custom string to php thingie, but that's the only thing outstanding. Flipping branches didn't break anything and the new field options look really good. Review my help text suggestions above, but other than that this should be good to go.

**Comment by JoryHogeveen** [comment]
> Instead of the PHP Date & Time Formatting, should we maybe reference them to the WordPress Codex one? https://codex.wordpress.org/Formatting_Date_and_Time (and/or both?)
Not sure, the documentation info is the same and I think most (novice) users will user WP default or a predefined format.

> Predefined would be 'select from a list of available formats'
Yep! Maybe a label change?

> WordPress default would mean it's defined under the General, Settings for the WordPress Installation
Yep! Maybe add a link to that setting page in s help tooltip somewhere? Or do you think this is clear enough?

Let me know if you find anything else! Great to hear all migration tests worked at your end as well.
Now that I think of it. Maybe also test ACT's? Since they fully rely on Pods fields for all data. @sc0ttkclark could you take a look at that? I think you know ACT's the best "under the hood".

**Comment by JoryHogeveen** [comment]
Also, Travis tests are still failing for some reason, I get the feeling it has something to do with ACT's..

**Comment by jimtrue** [comment]
yeah I'm terribly inexperienced with the ACTs.

This is what I'd do on the Help Text just for Date Field Format (since there's nothing there right now) and likewise on Time:

> **WordPress Default** is the format used in [Settings, General]([site-url]/wp-admin/options-general.php) under 'Date Format'. **Predefined Format** will allow you to select from a list of commonly used date formats. Custom will allow you to enter your own using the PHP Date/Time Strings. (link).

**Comment by JoryHogeveen** [comment]
@sc0ttkclark Want me to do a full indentation refactor? These files had a big refactor so why not..

**Pull request merged**
