### PR TITLE
Get rid of PHP4 constructor in widgets

### PR DESCRIPTION
**Pull request by Shelob9**
#3055

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Shouldn't we also be using __construct in our widgets here? Instead of the php4 constructors?

Our extend would still have to call parent::__construct with the args, but we also need to declare the args exactly as the parent class does in the function / phpdoc.

And is this backwards compatible with previous versions of WP?

**Comment by Shelob9** [comment]
@sc0ttkclark Good point re: backwards compat. Looking at the changeset in core, I think you are right: https://core.trac.wordpress.org/changeset/32990/trunk/src/wp-includes/widgets.php

**Comment by Shelob9** [comment]
@sc0ttkclark I refreshed with a proper `__construct()` the fact that `WP_Widget::__construct()` doesn't exists in 4.2 and earlier shouldn't be an issue right? Don't constructors always exist by magic?

**Comment by pglewis** [comment]
An omitted constructor is effectively the same and an empty constructor.

**Comment by sc0ttkclark** [comment]
If that's the case @pglewis then we should be set. Can someone verify though, just to be sure, that's what actually happens for < 4.3

**Comment by Shelob9** [comment]
Works as expected in WordPress 4.2.

**Pull request merged**
