### PR TITLE
Add pod_is_valid() to handle the $pod validation

### PR DESCRIPTION
**Pull request by sc0ttkclark**
`if ( pod_is_valid( $pod ) )` will check if `$pod` is a valid Pods() object and if the pod itself was found `->valid()`.

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Also added `pod_has_items( $pod )` which will check if a `$pod` has item(s) from a `find()` or `fetch( $id )`

**Comment by sc0ttkclark** [comment]
Ready for CR

**Comment by pglewis** [comment]
Is there an associated issue for this?

**Comment by sc0ttkclark** [comment]
No associated issue for this

**Pull request merged**
