### PR TITLE
Separate out html from PodsUI class in separate views.

### PR DESCRIPTION
**Pull request by unknownnf**
## Description

Separate out html from PodsUI class in separate views.

## PR checklist

- [x] I have tested my own code to confirm it works as I intended.
- [x] My code follows the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] My code follows the [WordPress Inline Documentation Standards](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/).
- [x] My code includes automated tests for PHP and/or JS (if applicable).

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
@unknownnf Assuming this is a draft since it has "WIP" in the title. Let me know when you think it's good to put my full attention on the review. Maybe you can update the PR with a status of how far along you are in your goal for the work.

**Comment by unknownnf** [comment]
@sc0ttkclark should be good to go now, wip was because my changes weren't tested and not sure if i messed up any.

**Comment by JoryHogeveen** [comment]
Is it already testable? Since I don't see any modifications in PodsUI.

**Review by sc0ttkclark — APPROVED** [review]

**Comment by sc0ttkclark** [comment]
This is a great start, we can go from here and implement the views into the PodsUI in some future work. For now, I'm drafting this PR until we catch it up with any of the latest changes from 2.8.x and 2.9

**Comment by JoryHogeveen** [comment]
Hi @sc0ttkclark 
You closed this, shouldn't it be drafted?

**Comment by sc0ttkclark** [comment]
It won't let me, it automatically closed.

**Comment by JoryHogeveen** [comment]
Probably because it's not rebranched yet. You deleted the release branch.

**Pull request closed without merging**
