### PR TITLE
Create Dockunit.json

### PR DESCRIPTION
**Pull request by tlovett1**
This adds a `Dockunit.json` file that runs the test suite in PHP 5.6 and 7.0 RC 1.

### CODE REVIEW

**Comment by Ramoonus** [comment]
the docker php version are not in line with the unit testing versions

**Comment by Ramoonus** [comment]
Travis-CI docker; http://blog.travis-ci.com/2015-08-19-using-docker-on-travis-ci

**Comment by sc0ttkclark** [comment]
@Ramoonus this is for experimental usage of https://dockunit.io/ outside of Travis-CI

**Comment by Ramoonus** [comment]
then it should be ignored from releases?

**Comment by tlovett1** [comment]
Travis CI docker isn't as flexible as dockunit and is pretty difficult to setup - http://docs.travis-ci.com/user/docker/

**Comment by tlovett1** [comment]
Also, dockunit lets you run the same containerized tests locally which is very difficult with Travis.

**Pull request merged**
