### PR TITLE
travis-ci with php 7 but allow failures

### PR DESCRIPTION
**Pull request by Ramoonus**
#2764

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Should `7` be `nightly` instead? Or not?

**Comment by Ramoonus** [comment]
alias :-)
http://docs.travis-ci.com/user/languages/php/

**Comment by sc0ttkclark** [comment]
Maybe we should do nightly then, since we'll have a need for nightly long term, even after 7 is released, right?

**Comment by Ramoonus** [comment]
true
nightly is an alias for 7
when 7 arrives, maybe they name the nightly 7.1 or 8

**Comment by sc0ttkclark** [comment]
I thought 7 was an alias for nightly, not the other way around. So when 7 is released, they remove the alias and 7 works as expected, and nightly pulls the next release in progress.

**Comment by Ramoonus** [comment]
either way
7 = nightly

ive updated my patch branch

**Comment by sc0ttkclark** [comment]
Reverted, please try again and validate the yml file here: http://lint.travis-ci.org/

**Comment by Ramoonus** [comment]
I found it strange that Travis was not testing the pull request
This explains

-----Oorspronkelijk bericht-----
Van: "Scott Kingsley Clark" <notifications@github.com>
Verzonden: ‎6-‎3-‎2015 01:09
Aan: "pods-framework/pods" <pods@noreply.github.com>
CC: "Ramon van Belzen" <ramoonus@zeelandnet.nl>
Onderwerp: Re: [pods] travis-ci with php 7 but allow failures (#2774)

Reverted, please try again and validate the yml file here: http://lint.travis-ci.org/

---

**Pull request merged**
