### PR TITLE
Remove Limit of 5 in get_template_titles for #3157

### PR DESCRIPTION
**Pull request by jimtrue**

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
I'm down with increasing this, but I'd caution to set some sort of limit, perhaps a high limit of 100? Overridden by a filter if someone *really wants* more.

**Comment by sc0ttkclark** [comment]
Fixes #3157

**Comment by sc0ttkclark** [comment]
`release/3.0` PR - #3166

**Comment by jimtrue** [comment]
The functionality of being able to select your templates from the list was broken as it currently stood. If the template exists, it needs to be in the drop down. This should be modified to use the same logic as the choose template in the Pods Shortcode dialog.

**Pull request merged**
