### PR TITLE
Remove CodeClimate integration

### PR DESCRIPTION
**Pull request by Ramoonus**

### CODE REVIEW

**Comment by JoryHogeveen** [comment]
No CodeClimate?

**Comment by Ramoonus** [comment]
it doesn`t work automatically

**Comment by JoryHogeveen** [comment]
Why not? We only need to create an account and it will.

**Comment by Ramoonus** [comment]
if Scott could try to active it on the CC site

**Comment by Ramoonus** [comment]
you don`t need the files to have testing run

**Pull request merged**
