### PR TITLE
Auto template: saved settings not initializing correctly on load

### LINKED ISSUE #4143: Auto Template: not properly initializing saved options in the 2.7 branch, defaulting to first in list
PR: #4151 

Auto Template is not Saving selection under 2.7 branch, defaulting to first in list submitted via Slack by jimtrue

### PR DESCRIPTION
**Pull request by pglewis**
Fixes #4143

### CODE REVIEW

**Comment by pglewis** [comment]
In the case of pfat values, `$args->value` is a single string and not an array.  Commit reflects this possiblity.

**Comment by sc0ttkclark** [comment]
This feels familiar, is there another PR or something open with a similar tweak in it from me?

**Comment by sc0ttkclark** [comment]
Aha, indeed!

https://github.com/pods-framework/pods/pull/3634/files#diff-1ca5a4ce2807504d1a97028fc9959802R1187

**Comment by pglewis** [comment]
Ha!  Good to know I was actually close.  

Should I just copy that solution for this one?  It's not an atomic commit, so can't just cherry-pick it over.

**Comment by pglewis** [comment]
@sc0ttkclark: I did another commit that primes `$selected` as `false` above the conditionals.

**Pull request merged**
