### PR TITLE
Do not display metagroup if all fields are set to hidden.

### PR DESCRIPTION
**Pull request by JoryHogeveen**
Fixes: https://github.com/pods-framework/pods/issues/1614

### CODE REVIEW

**Comment by JoryHogeveen** [comment]
Other option is to set the metagroup to hidden with the hidden_meta_boxes filter:
https://developer.wordpress.org/reference/hooks/hidden_meta_boxes/

**Comment by sc0ttkclark** [comment]
Are there other areas we can/should do this?

**Comment by JoryHogeveen** [comment]
Not that I know of. Post types are the only ones that use metaboxes

**Comment by JoryHogeveen** [comment]
Wait with merging.
I would like to check what happens with a checkbox field since they are normally set to false (or deleted) if no post value is found.

**Comment by JoryHogeveen** [comment]
Tested checkboxes aswell, looks like all is working fine!

**Pull request merged**
