### PR TITLE
Fix opcache names and add OPcache

### PR DESCRIPTION
**Pull request by szepeviktor**
See #3864

### CODE REVIEW

**Comment by szepeviktor** [comment]
Major problems with Travis tests.

**Comment by pglewis** [comment]
> Major problems with Travis tests.

#3874, it's a testing issue.

**Comment by Ramoonus** [comment]
does this overlap with W3TC?

**Comment by szepeviktor** [comment]
> does this overlap with W3TC?

No, it is just for pure extension based caches.

See https://github.com/wp-cli/wp-cli/pull/3637/files for W3TC object caches.

**Pull request merged**
