### PR TITLE
Add SQLite testing for #3336

### PR DESCRIPTION
**Pull request by sc0ttkclark**
Will adjust code and continue testing to see how many issues there may be.

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Need to figure out what additional tweaks are needed in order to properly test against SQLite, one of which means we need to pull an additional plugin during the build script:

https://wordpress.org/plugins/sqlite-integration/

Also need to move `db.php` to `/wp-content/` set `DB_FILE` / `DB_DIR` in wp-config.php per installation instructions: https://wordpress.org/plugins/sqlite-integration/installation/

**Comment by pglewis** [comment]
This appears to pass already and we create ACTs in the tests, no?  Might need some digging.

**Comment by sc0ttkclark** [comment]
Yeah I'm betting it's not even using SQLite, still needs that integration stuff implemented in the case of `sqlite` as the DB type (in the build .sh script)

**Comment by sc0ttkclark** [comment]
Closing this, a bit too much effort necessary for it.

**Pull request closed without merging**
