### PR TITLE
Try and get single select to work with [each] templating

### LINKED ISSUE #4507: Single Select vs. Multi Select in Files Fields or Relationships can't handle EACH
Single Select vs. Multi Select in Files Fields or Relationships can't handle EACH submitted via Slack by jimtrue

### PR DESCRIPTION
**Pull request by sc0ttkclark**
## Description
Single select relationships don't work for `[each]` when templating.

Fixes #4507

## ChangeLog
Support single select relationships in templates when using `[each]`

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
That's progress :)

OK so the only remaining issue here is special tags like _img while in `[each]`?

**Comment by jimtrue** [comment]
Yep, seems to be only the {@_img} and {@_src} which means you can't get the images to show in a single image setup inside the each. You do have access to the Image ID with {@ID} so that should work as a fallback.

**Comment by JoryHogeveen** [comment]
@jimtrue If you have the time, my latest comment fixes file types, could you test as well?

**Comment by sc0ttkclark** [comment]
Looks good, thanks @JoryHogeveen

**Pull request merged**
