### PR TITLE
Fix for roles and capabilities

### PR DESCRIPTION
**Pull request by adleviton**
Wordpress user was seeing all other user's records, despite having 'pods_edit_others_mypod' and 'pods_delete_others_mypod' unchecked under settings.

## ChangeLog
TBD

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style.
- [ ] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by adleviton** [comment]
Just submitted a pull request based on this this that also fixes the same issue when reordering: https://github.com/pods-framework/pods/pull/5392

**Comment by JoryHogeveen** [comment]
After testing this it's still not 100%.
The edit part seems to work but deleting (even of the user doesn't have the proper capabilities) is always possible when a user can edit.
@sc0ttkclark This one might need a larger refactor to work properly like WP post types. Any thoughts?

**Comment by sc0ttkclark** [comment]
Punting this to next release

**Comment by JoryHogeveen** [comment]
Hello @adleviton 
I'm sorry but I made a separate PR for this issue that includes a refactor of this whole code block.
I will therefore close this PR. If you have the time, could you test #5504 and verify it also works for you?

**Pull request closed without merging**
