### PR TITLE
Merge auto activate components fixes

### LINKED ISSUE #3446: Ehancement: Activate Pods Templates on Pods Activation for User Experience
PR: #4060

Ehancement: Activate Pods Templates on Pods Activation for User Experience submitted via Slack by jimtrue

It's fairly easy to miss this for new & beginning users of Pods. This would be a quality of life improvement. If a developer or anyone else didn't need Auto Templates or Pods Templates, they could very easily disable this component.

### PR DESCRIPTION
**Pull request by sc0ttkclark**
Fixes #3446

### CODE REVIEW

**Comment by pglewis** [comment]
Ready for the next round of testing for @jimtrue?

**Comment by jimtrue** [comment]
Working support issues at the moment, but sure I will test this again today so we can merge ;)

**Comment by jimtrue** [comment]
Nope, still not working. Dropping all tables from WordPress so 'fresh' install. Activating Pods plugin should recognize it's never been activated on this installation of WordPress and I'm not getting 'Templates' auto enabled.

**Comment by sc0ttkclark** [comment]
Go to Pods Admin > Settings > Cleanup > Do the reset/cleanup tool. Does it show up activated?

**Comment by jimtrue** [comment]
It does then, but it doesn't on an initial plugin install.

**Comment by jimtrue** [comment]
Unless there's something file-based we're writing, because dropping all the database tables is the same as a fresh WordPress install and plugin activation.

**Comment by sc0ttkclark** [comment]
It runs the initial plugin install through that code, so we'll have to see what's up with your initial test.

**Comment by jimtrue** [comment]
I did a git clone of our plugin off the branch above. That's the only thing in my WP installation. I dropped database tables this time to force a new WP install (because I wasn't sure the WordPress Reset was enough), activate the Pods Plugin and it should be doing _exactly_ what your Pods Cleanup & Reset is doing (or at least what the Deactivate & Delete is doing).

**Comment by sc0ttkclark** [comment]
Will have to debug the path for that, maybe something is happening with the pathway on initial install that doesn't happen with reset/install

**Comment by jimtrue** [comment]
Well from our own help text:

> This will reset Pods settings, removes all of it's data, and performs a fresh install.

>Please Note: This does not remove any items from any Post Types, Taxonomies, Media, Users, or Comments data you have added/modified.

And Deactivate/Delete:

>This will delete Pods settings, data, and deactivate itself once done. Your database will be as if Pods never existed.

>Please Note: This does not remove any items from any Post Types, Taxonomies, Media, Users, or Comments data you have added/modified.

So the second sounds more like an actual Fresh install. So neither of our two options above will actually clear post_meta that we've added with Pods?

**Comment by jimtrue** [comment]
I know my second question is a separate issue, but we really need to be very clear about what both of those do and the proper way to 'clean up' your database to remove Pods.

**Comment by sc0ttkclark** [comment]
Ready for retest

**Comment by jimtrue** [comment]
Worked!

**Comment by jimtrue** [comment]
Was there any other situations with this one, you'd like me to test?

**Comment by sc0ttkclark** [comment]
I don't think so, this was the only one

**Comment by jimtrue** [comment]
Just to be on the safe side, I also did the disable templates and deactivate plugin and reactivate and it stayed disabled (expected)
Clear Pods Data & Reset, stayed disabled (also expected)
Delete Pods Data & Deactivate, re-enabled on activating plugin (expected).

**Pull request merged**
