### PR TITLE
Fix checkbox/radio position on Pods admin and setting pages

### LINKED ISSUE #4711: Checkbox lists CSS in dashboard slightly off
Checkboxes appear slightly below the text. This is from a custom settings admin page.

screen shot 2018-01-15 at 18 43 48

### PR DESCRIPTION
**Pull request by JoryHogeveen**
Fixes #4711

### CODE REVIEW

**Comment by JoryHogeveen** [comment]
I did not commit the compiled CSS files since this does not seem to compile the same as Pods currently has. Will check this further.

**Comment by pglewis** [comment]
This doesn't straighten out the issue for me on a settings page (I rebuilt the CSS locally).

**Comment by pglewis** [comment]
Yeah, somehow I ended up with some sort of double-slit experiment.  Does work for me now.

**Comment by pglewis** [comment]
Could probably use @sc0ttkclark's merge-fu, I think some of the conflicts with setup-edit are from the PHPCS changes and I'd rather not muck up the conflict resolution.

**Comment by pglewis** [comment]
Changelog: Fix checkbox misalignment on custom settings pages (#4711)

**Pull request merged**
