### PR TITLE
Fix for issues when Pods shortcodes are embedded in HTML

### LINKED ISSUE #4324: Templates inside HTML broken after Updating Pods
```
<div class="free-it">
    <div class="free-th">
        <a target="blank" href="[if url]
{@url}
[else]
{@permalink}
[/if]"><img src="{@image._src}"></a>
    </div>
    <div class="free-ct"><a target="blank" href="[if url]
{@url}
[else]
{@permalink}
[/if]"><span>{@post_title}</span></a></div>
</div>
```

**Becomes this on the front end:**

```
<a target="blank" href="[pod_if_field id=" 56428"=""  field="url" index="{_index}" seq="2" ]dqp7qhvybh0ncltlbhnlxq0ke0bwzxjtywxpbmt9dqo="[/pod_if_field]
```

### PR DESCRIPTION
**Pull request by pglewis**
Fixes #4324

### CODE REVIEW

**Comment by pglewis** [comment]
@jamesgol: Can I get a sanity check that this change won't re-break the things you fixed?

**Comment by jamesgol** [comment]
I'm away on vacation, but looking at the code it won't break what was previously fixed but it looks like a band aid for the way the [if], [else], etc. tags are implemented.

You might also be able to just do do_shortcode( $content, true );

**Comment by pglewis** [comment]
> You might also be able to just do do_shortcode( $content, true );

Nah, that'll force it to always escape out the shortcode as entities, giving the same result.  We really can't have it call through to `do_shortcodes_in_html_tags()` with any of our shortcodes still potentially embedded inside HTML, which will happen fairly often in templates.  `wp_kses_attr_parse` will choke and there really doesn't seem to be a kosher way to sneak around it.  This might be the least amount of duct-tape to do it.

**Comment by jimtrue** [comment]
Fixes #4307, #4308 and #4324. #4303 is still outstanding for resolution.

**Pull request merged**
