### PR TITLE
Prevent storing autoloaded transients in the DB

### PR DESCRIPTION
**Pull request by sc0ttkclark**
## Description

Many Pods transients have no expiration on them, which is fine in the case of using Pods Alternative Cache, but when stored in the database with large configs, this can be problematic as they are autoloaded in bulk.

## Changelog text for these changes

Fixed: Prevent Pods from saving transients to the options table and having them autoloaded.

## PR Checklist

- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Review by JoryHogeveen — DISMISSED** [review]

**Comment by JoryHogeveen** [comment]
Looks good to me.
The only thing I'm wondering is whether this would actually improve loading.
I can imagine transients for registering Pods should always be loaded and thus would be faster if autoload was enabled since it doesn't require an extra query then.

**Comment by sc0ttkclark** [comment]
The primary problem is autoload gets bloated and then has problems from MySQL limits. It's a trade off :(

**Comment by JoryHogeveen** [comment]
Then maybe we should take a look at how to prevent bloating autoload but still add autoloading to transients that always need to be loaded.
This feels like an incomplete fix.

**Comment by JoryHogeveen** [comment]
@sc0ttkclark  Do we have some form of overview of what transients are made throughout Pods?

**Comment by jaycollier** [comment]
For what it's worth, I described the large autoloaded transient tables in our database in this ticket:

https://wordpress.org/support/topic/autoloading-database-tables/#post-13553380

**Comment by jaycollier** [comment]
Hi!

Does the most recent note mean this is being considered for an upcoming release? I'm not experienced with GitHub to know what this means...

sc0ttkclark force-pushed the main branch from 220e6ac to a2aeac9 26 days ago

...  and I didn't see 5846 in the changelog.

Thanks for considering this.

-Jay

**Comment by JoryHogeveen** [comment]
@sc0ttkclark 
Why was this punted to Backlog?

**Comment by sc0ttkclark** [comment]
I'm not sure why this went to backlog, it should have just been moved to the next milestone. This PR needs further review on how we can separate things we do want auto-loaded versus ones that we don't.

**Comment by jaycollier** [comment]
Thank you so very much for the autoload improvements in 2.8. I see that there was a lot of work involved, but it has reduced our autoload significantly! Very much appreciated.

**Pull request closed without merging**
