### PR TITLE
Introducing QUnit 1.20.0

### PR DESCRIPTION
**Pull request by Ramoonus**

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
@Ramoonus What's left here?

**Comment by Ramoonus** [comment]
the unit tests itself,
QUnit and it`s included are present

**Comment by pglewis** [comment]
I'm going to leave this here for the moment but I'm currently leaning heavily toward mocha in the JS testing stack.

**Comment by sc0ttkclark** [comment]
Going to close this as maybe later, we have no tests right now and we're looking at a complete JS rewrite when we revamp our UI with REST API, we can write tests and introduce it at that point.

**Pull request closed without merging**
