### PR TITLE
phpunit multiple versions

### PR DESCRIPTION
**Pull request by Ramoonus**

### CODE REVIEW

**Comment by Ramoonus** [comment]
don`t pull yet

**Comment by sc0ttkclark** [comment]
@Ramoonus it looks like it passes:
https://travis-ci.org/pods-framework/pods/builds/239562673

**Comment by Ramoonus** [comment]
I would like to make a bash script or 2 more, to tidy up things

**Comment by Ramoonus** [comment]
you approved, ready when you say to merge

**Pull request merged**
