### PR TITLE
Update Pods Logos #2534 

### PR DESCRIPTION
**Pull request by NikV**
Please see: https://github.com/pods-framework/pods/issues/2534

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Is this ready for merge?

**Comment by NikV** [comment]
Yep, seems ready to me.

**Comment by Shelob9** [comment]
@NikV You missed two logos:

https://github.com/pods-framework/pods/blob/master/ui/images/pods-logo-notext-rgb-transparent.png
https://github.com/pods-framework/pods/blob/master/ui/images/pods-logo-notext-rgb.png

Please update this PR with a replacement for all logos

**Comment by jimtrue** [comment]
Use These:

pods-logo-notext-rgb
pods-logo-notext-rgb-transparent

**Comment by Shelob9** [comment]
Fixes #2534

**Pull request merged**
