### PR TITLE
Simplify logic for frontier [if] shortcodes

### PR DESCRIPTION
**Pull request by jamesgol**
Complicated issue with nested shortcodes that fall under non-pods shortcodes (ie: inside a builder shortcode).  The frontier output isn't available to the typical WordPress do_shortcodes since
it is obfuscated in base64.

Also eliminates some code duplication, seeing that same array of tags all those times was driving me crazy.

Related to #4303

### CODE REVIEW

**Comment by jamesgol** [comment]
I'm really not sure if the PODS_SHORTCODE_ALLOW_SUB_SHORTCODES check is desired since it doesn't jive exactly with existing behavior but does fit the docs.

In my test I have the following:
```add_shortcode( 'jmgtest', 'jmgtest_short' );
function jmgtest_short( $a = null, $content = null ) {

	$output = do_shortcode( $content );

	return $output;
}

add_shortcode( 'jmginside', 'jmginside_short' );
function jmginside_short( $a, $content ) {
	$output = '<br>JMG shortcode text';
	return $output;
}
```
Pretty basic, the 'jmgtest' shortcode simulates what a builder shortcode would do.

So in the following test:
```
[jmgtest]
[if whatever]
[jmginside]
[/if]
[/jmgtest]
```
On current 2.x the '[jmginside]' code will not be executed but will be displayed raw.

In this test:
```
[if whatever]
[jmginside]
[/if]
```
On current 2.x the '[jmginside]' code is executed and the output is displayed.

**Comment by jimtrue** [comment]
@jamesgol So the issue is with if/else/if, not if/if ?

**Comment by jamesgol** [comment]
I'm away for the week on vacation at the Oregon coast.  I'll get back on this when I return.

**Comment by jamesgol** [comment]
If this goes in the changes in #4335 can be safely reverted.

**Comment by pglewis** [comment]
BTW: this was originally made against 2.x.  I naively tried to just change the base to 2.7 through GitHub, which obviously didn't work.  Not sure of the best way to iron that out.

**Comment by jamesgol** [comment]
Closing in favor of #4423

**Pull request closed without merging**
