### PR TITLE
Pods Help page: swap old forum feed with wordpress.org feed, fix warnings from SimplePie/PHP 7+

### LINKED ISSUE #5172: Remove the pods.io forum feed from the Pods help page and Update for More Support Items
If WordPress provides a feed for their built-in support forums I assume we want to insert that in its place.

### PR DESCRIPTION
**Pull request by pglewis**
Fixes #5172

### CODE REVIEW

**Comment by pglewis** [comment]
There is the potential to "fix" #4363 with something like: 

```
// Temporarily turn off warnings and then restore, due to a bug in
// SimplePie's date parser with PHP 7.1+
// See: https://github.com/pods-framework/pods/issues/4363
$old_error_reporting = error_reporting( ~E_WARNING );
$max_items = $feed->get_item_quantity( 10 );
error_reporting( $old_error_reporting );
...
```

... which is effectively "fixing" the check engine light but putting a piece of tape over it so you can't see it.  I would normally be against this sort of thing, but it's a non-vital area and we can't fix SimplePie.

**Comment by sc0ttkclark** [comment]
Doesn’t @$ also silence warnings?

**Comment by pglewis** [comment]
The only other question is if we want to mark resolved issues in the feed via CSS (the title from the feed will be wrapped in a span with the "resolved" class).

**Comment by sc0ttkclark** [comment]
That's a good idea, not a must-have but if you have time for it outside Gb stuff then that's fine.

**Comment by jimtrue** [comment]
If we add the following CSS:
```
ul.ul-disc span.resolved:before {
    content: "Resolved: ";
}
```

This will put Resolved in front of the resolved tickets. @nicdford or @JoryHogeveen if you guys wanna pretty that up anymore, add it in :)

**Pull request merged**
