### PR TITLE
Switch back to 'taxonomy_format_type' possible fix for #2747

### LINKED ISSUE #2747: incorrect work function $pods->field( "xxx.term_id" )
Create a Custom Post Type the name of demo
and Custom Taxonomy named demo1
associate their demo uses demo1

in version 2.4.3-b-1 code works and provides a list of related records from demo1

```
$pods = pods('demo', array('limit' => -1));
while ( $pods->fetch() ) {
    foreach ( $pods->field( "demo1.term_id" ) as $host ) {
        echo "demo1: ".$host."<br>";
    }
}
```
Version 2.5.1 provides ID is always the first record of the demo1
all this because of the replacement file PodsAPI.php

old version
```
                foreach ( $taxonomies as $taxonomy ) {
                    $fields[ $taxonomy->name ] = array(
                        'name' => $taxonomy->name,
                        'label' => $taxonomy->labels->name,
                        'type' => 'taxonomy',
                        'pick_object' => 'taxonomy',
                        'pick_val' => $taxonomy->name,
                        'alias' => array(),
                        'hidden' => true,
                        'options' => array(
                            'taxonomy_format_type' => 'multi'
                        )
                    );
                }
```
new version
```
                foreach ( $taxonomies as $taxonomy ) {
                    $fields[ $taxonomy->name ] = array(
                        'name' => $taxonomy->name,
                        'label' => $taxonomy->labels->name,
                        'type' => 'taxonomy',
                        'pick_object' => 'taxonomy',
                        'pick_val' => $taxonomy->name,
                        'alias' => array(),
                        'hidden' => true,
                        'options' => array(
                            'pick_format_type' => 'multi'
                        )
                    );
                }
```

'taxonomy_format_type' => 'multi'
replaced by
'pick_format_type' => 'multi'

what to do?
how to get a list of related records?

### PR DESCRIPTION
**Pull request by Shelob9**
We need to make sure this fix for #2747 actually fixes #2747 and it also doesn't cause a regression on #2607 .

### CODE REVIEW

**Comment by Shelob9** [comment]
@sc0ttkclark I'm reassigning this to you as it needs unit tests via #2749

**Comment by NikV** [comment]
Alright so I did some testing. From this I got an array with field and when I examined the array, I got all the terms that were in the taxonomy. Code used ` $podss->field( 'tags2' );`

**Comment by NikV** [comment]
Can confirm that everything should work with Pods Frontier as well with {@tags2}. The output is the terms assigned:  tag and tag2.

**Comment by Shelob9** [comment]
@NikV Can you please describe how you tested this with magic tags? Please detail how you tested it with one term and multiple terms assigned. Did you test with and without an each loop in both cases?

**Comment by NikV** [comment]
I tested the magic tags in the Template system and with the [pods] shortocde, both with the same results. The terms are displayed or the single term in the taxonomy is displayed on the frontend with just the name of the the term(s) selected. Not each loops used in any case

**Comment by Shelob9** [comment]
I tested with this follows:
```
$pods =  pods( 'seafood_products', 149 );
var_dump(  $pods->field( 'seafood_category' ) );
var_dump( wp_get_object_terms( 149, 'seafood_category' ) );
```

I get the following bad results with multiple or single term associated with post ID 149
L2 (the test with `Pods::field()` returns an empty array. L3 (the test using `wp_get_object_terms()` show

**Pull request merged**
