### PR TITLE
Update font icon

### PR DESCRIPTION
**Pull request by ghost1227**
Issue #2534

### CODE REVIEW

**Comment by Shelob9** [comment]
@ghost1227 I think this PR makes the logo not vertically aligned properly.

Before:
screen shot 2015-03-03 at 5 20 52 pm

After:
screen shot 2015-03-03 at 5 20 30 pm

**Comment by jimtrue** [comment]
This is what I'm seeing from a fresh installation of this patch, so maybe you have something left over @Shelob9 ?

screenshot 2015-03-03 17 30 46

**Comment by jimtrue** [comment]
@ghost1227 Can you replace that icon with this one? (Now that I see it in the final product, it does need to be reversed without the circle around it.

https://drive.google.com/file/d/0B2iTBwlukqFtYi1UOEY2Ui1kVFU/view?usp=sharing

**Comment by ghost1227** [comment]
Sure thing!

---Sent from Boxer | http://getboxer.com

On March 3, 2015 at 3:50:25 PM MST, Jim True <notifications@github.com> wrote:@ghost1227 Can you replace that icon with this one? (Now that I see it in the final product, it does need to be reversed without the circle around it.  https://drive.google.com/file/d/0B2iTBwlukqFtYi1UOEY2Ui1kVFU/view?usp=sharing  —Reply to this email directly or view it on GitHub.

**Pull request merged**
