### PR TITLE
pods_clean_name cleanup for 2.x

### PR DESCRIPTION
**Pull request by quasel**
see #3012

### CODE REVIEW

**Comment by quasel** [comment]
#3012

**Comment by sc0ttkclark** [comment]
Looks good

**Comment by sc0ttkclark** [comment]
3.0 PR: #3022

**Comment by quasel** [comment]
thx ;) you gave very clear instructions - not really used to deal with Regex

**Comment by sc0ttkclark** [comment]
Going to wait for Travis-CI build to completely / officially pass but all tests were passing last I checked.

**Pull request merged**
