### PR TITLE
css improvements (csslint)

### PR DESCRIPTION
**Pull request by Ramoonus**
https://codeclimate.com/github/pods-framework/pods/issues?category=bugrisk&engine=csslint

### CODE REVIEW

**Comment by Ramoonus** [comment]
please wait till I`m done :-)

**Comment by sc0ttkclark** [comment]
@Ramoonus what's left?

**Comment by Ramoonus** [comment]
#3749 
#3744

**Comment by Ramoonus** [comment]
let`s continue in the other issues

**Comment by JoryHogeveen** [comment]
Related PR: #3968

**Pull request closed without merging**
