### PR TITLE
Fixing Help text for HTML fields enable wpautop

### LINKED ISSUE #4089: HTML Help Text has an error for wpautop
HTML Help Text has an error for wpautop submitted via Slack by jimtrue

### PR DESCRIPTION
**Pull request by jimtrue**
Fixes #4089

### CODE REVIEW

**Comment by jimtrue** [comment]
Let's go with Jory's his is more consistent with the other help text for Paragraph and Wysiwyg #4091

**Comment by JoryHogeveen** [comment]
@jimtrue Or change all other strings as well since `<p>...</p>` is also found in the WP codes.
In any case: If we want visible HTML in a string it should be wrapped int `esc_html__()` and not `__()`

**Comment by JoryHogeveen** [comment]
@sc0ttkclark What happened with this PR? I see a lot of commits that don't seem to be related to this issue.

**Comment by sc0ttkclark** [comment]
I merged 2.7 into this and merged this into 2.7

**Pull request merged**
