### PR TITLE
Automate version release process for 2.x branch 

### LINKED ISSUE #2648: Automate release process in 2.x
* Update version number change #2571 
* Update translation strings
* Commit those changes
* Tag
* Push To SVN
* Tag SVN

### PR DESCRIPTION
**Pull request by Shelob9**
resolves #2648

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Does this work?

**Comment by Shelob9** [comment]
I think. I can't test the whole thing without doing a release. It's based on acknowledge-me's deploy script, which works swiminigly.

**Comment by sc0ttkclark** [comment]
Let's test it this week for Pods 2.5.2 release. Tomorrow or Friday should work. What's the process?

**Comment by Shelob9** [comment]
@sc0ttkclark See https://github.com/pods-framework/pods/pull/2653#commitcomment-9435500

**Comment by sc0ttkclark** [comment]
So we have to put the old_version as whatever the alpha version was in 2.x branch, right?

**Comment by Shelob9** [comment]
@sc0ttkclark Oops those docs are behind the improvements @jamesgol did. All we have to do now is changes version in package.json and git_tag in package.json and run `grunt release`

**Comment by sc0ttkclark** [comment]
So the steps leading up to running this, should be:

1. Finish all release work
2. Merge 2.x into master
3. Run this script?

Or do 2 and 3 get switched, or is that all part of it?

**Comment by Shelob9** [comment]
@sc0ttkclark I updated those docs, will make into real docs later tonight or tomorrow. But yes you are right. This is designed to happen after we merge 2.x into master. It updates version numbers, commits that, tags the master branch, and then pushes all to GitHub and WPORG SVN.

I can walk you through it when we do it.

**Comment by sc0ttkclark** [comment]
Great, I'll setup the 2.5.2 PR.

**Comment by Shelob9** [comment]
Closeing as #joshfail will redo

**Pull request closed without merging**
