### PR TITLE
Allow quotes in relationship custom simple fields

### LINKED ISSUE #2360: Simple Relationship (list) won't save a value with double quotes
This may be related to the spirit of #1943. I've also posted this at https://wordpress.org/support/topic/how-do-i-get-the-lable-instead-of-the-value-from-a-list-with-get_post_meta.

My issue is that if I have double quotes in the value of a list item, it won't save when I update the post; it returns an empty field instead. In the past I got away with these items:

1|5.5" x 8.25"
2|6" x 9"
3|5.5" x 7.5"
4|5.25" x 7"
5|5.375" x 7"
6|5.5" x 7"
7|7" x 9"
8|7.25" x 9.5"
9|8" x 10"
10|9" x 7"

Those are the trim of a book (its size), and the reason this worked is because I would use a magic tag, `{@trim}`, and it gets the label. That works, so I didn't think about it much. Now I am moving my templates into the theme, and `<?php echo get_post_meta( get_the_ID(), 'trim', true); ?>` returns the value, which in this case isn't helpful.

As @Shelob9 pointed out, there are ways to get the label, but I'd rather figure out how to save the value I want, and just use `get_post_meta`.

I've tested the following modifications to the list:

|5.5" x 8.25"
6" x 9"|6" x 9"
5.5 x 7.5|5.5" x 7.5"
5.25" x 7"

Of those four, only the third, `5.5 x 7.5|5.5" x 7.5"`, will save the value. That may work in the meantime, but of course we would prefer to have the double quotes to refer to the inches in the size.

I've tried escaping the double quotes, with back slashes, but that didn't change anything. Suggestions? ^_^

### PR DESCRIPTION
**Pull request by jamesgol**
Fixes #2360
Related to #2361

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Not sure if we have simple rel tests with items that have quotes, we should add them though before moving forward, to ensure moving parts continue to work as expected.

**Comment by jamesgol** [comment]
I'll add some tests here if I get a chance this weekend sometime

**Comment by sc0ttkclark** [comment]
Add the test simple relationship field here in this array:

https://github.com/pods-framework/pods/blob/feature/2360-relationship-quotes/tests/includes/testcase.php#L141

And then add the test value here in the `'data'` array:

https://github.com/pods-framework/pods/blob/feature/2360-relationship-quotes/tests/includes/testcase.php#L324

**Comment by jamesgol** [comment]
Forgot how complicated the pods traversal tests are.  Spent a bunch of time on it today getting nowhere, looks like I'll have to work through and re-learn how everything gets set up in order to implement.

**Comment by pglewis** [comment]
Feel free to take notes and brainstorm on directions we could possibly take to make adding tests easier.  That's a huge issue/set of issues in itself.

**Comment by jamesgol** [comment]
The traversal tests won't easily work with the custom-simple fields, it looks like those tests do as much testing of the testing suite as of the Pods code.

I'm working on just a set of tests that only tests all the custom-simple fields with various parameters.

**Comment by JoryHogeveen** [comment]
Is this still valid since DFV?

**Comment by jamesgol** [comment]
I suspect it is partially valid.  Will have to revisit it tonight/tomorrow.

**Comment by quasel** [comment]
is this still an issue? @jamesgol - been loooong night :P sorry was too tempting ^^

**Pull request closed without merging**
