### PR TITLE
travis-ci: include php 7.2 in test matrix for PHPUnit

### PR DESCRIPTION
**Pull request by Ramoonus**

### CODE REVIEW

**Comment by Ramoonus** [comment]
waiting for it to appear in https://github.com/php-build/php-build/tree/master/share/php-build/definitions

**Comment by sc0ttkclark** [comment]
@Ramoonus it looks like it passes:
https://travis-ci.org/pods-framework/pods/builds/239562673

**Comment by Ramoonus** [comment]
try again
alpha 1 is out
building should work

**Comment by Ramoonus** [comment]
works now

**Comment by sc0ttkclark** [comment]
Might need a tweak?

**Comment by Ramoonus** [comment]
needs a reload to build

**Comment by Ramoonus** [comment]
it failed although on the net its in phpenv

**Comment by sc0ttkclark** [comment]
OK, will revisit after a day or so and try again

**Comment by Ramoonus** [comment]
okay php 7.2 is now available for the build environment
currently it hangs on xdebug

**Comment by Ramoonus** [comment]
I messed up, will try again

**Pull request closed without merging**
