### PR TITLE
PHPUnit 6 update (from 4)

### PR DESCRIPTION
**Pull request by Ramoonus**
Pro:
faster, better, stronger 

Cons:
Compared to PHPUnit 5, drops support for PHP 5.6

### CODE REVIEW

**Comment by Ramoonus** [comment]
seems to fail on WP:
PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in /tmp/wordpress-tests-lib/includes/testcase.php on line 15

**Comment by Ramoonus** [comment]
restarting the build

**Comment by Ramoonus** [comment]
just restarted the build

**Comment by Ramoonus** [comment]
waiting for https://core.trac.wordpress.org/ticket/39822

**Comment by Ramoonus** [comment]
patch seems to be from WP 4.8 onwards
so we are technically limited for now

**Comment by Ramoonus** [comment]
found a trick;
https://github.com/sebastianbergmann/phpcpd/blob/master/.travis.yml

**Comment by Ramoonus** [comment]
If I look at https://github.com/WordPress/wordpress-develop/blob/master/.travis.yml #L58
there is some nice trick at line 58

**Comment by sc0ttkclark** [comment]
I'd be interested in seeing how that trick works.

**Comment by Ramoonus** [comment]
#4286

**Pull request closed without merging**
