### PR TITLE
No max-length for default field value

### LINKED ISSUE #3729: Default Value Field for Text Editor field limited to 255 characters
Default Value Field for Text Editor field limited to 255 characters submitted via Slack by jimtrue

### PR DESCRIPTION
**Pull request by JoryHogeveen**
Fixes #3729

### CODE REVIEW

**Comment by JoryHogeveen** [comment]
@sc0ttkclark maybe a good idea to match the length of the default value with the field setting if it's available. Like to hear your thoughts on this.

**Comment by sc0ttkclark** [comment]
Don't think there's going to be an easy way to do this, but this is a quick solution for the biggest issue.

**Comment by JoryHogeveen** [comment]
@sc0ttkclark Maybe add a `@todo` in there for future review?

**Comment by sc0ttkclark** [comment]
Sure, that sounds good.

**Pull request merged**
