### PR TITLE
Allow where arrays to properly traverse

### LINKED ISSUE #2582: Related meta_value traversal not completing in find() with array params.
When doing a find using the following:

``` PHP
    $params = array(
        "where" => array(
            array(
                "field"   => "location.country",
                "value"   => "ZA",
                "compare" => "="
            )
        )
    );
```

The query traverses correctly joins ``wp_postmeta` AS `location_country` ON `location_country`.`meta_key` = 'country'` but it doesn't add the meta_value compare in the WHERE. Instead it keeps the traversal syntax `WHERE ( ( `location`.`country` = 'ZA' )...` resulting in a "Unknown column 'location.country' in 'where clause'"
Here's the full SQL generated:

``` SQL
SELECT DISTINCT
`t`.*
FROM `wp_posts` AS `t`

    LEFT JOIN `wp_podsrel` AS `rel_location` ON
        `rel_location`.`field_id` = 1898
        AND `rel_location`.`item_id` = `t`.`ID`

    LEFT JOIN `wp_posts` AS `location` ON
        `location`.`ID` = `rel_location`.`related_item_id`


    LEFT JOIN `wp_postmeta` AS `location_country` ON
        `location_country`.`meta_key` = 'country'
        AND `location_country`.`post_id` = `location`.`ID`

WHERE ( ( `location`.`country` = 'ZA' ) AND ( `t`.`post_type` = "review" ) AND ( `t`.`post_status` IN ( "publish" ) ) )


ORDER BY `t`.`menu_order`, `t`.`post_title`, `t`.`post_date`
```

### PR DESCRIPTION
**Pull request by jamesgol**
Fixes #2582

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
We aren't unit testing query_fields() via find() where arrays, but we should adjust unit tests for that and retest this fix.

**Comment by Shelob9** [comment]
Punting to 2.5.3 due to lack of tests.

**Comment by sc0ttkclark** [comment]
It wouldn't take much work to copy the existing traversal tests and convert them to using 'where' arrays, I'll do that as soon as I get another chance this week.

**Comment by sc0ttkclark** [comment]
The change in this PR masks the real issue, the query_field method does not traverse into the related pods / fields to properly add the prefix / suffix, it needs a little abstraction there into something like query_field_level

**Comment by sc0ttkclark** [comment]
Going to close this in favor of #3033

**Pull request closed without merging**
