### PR TITLE
Roles AJAX data

### LINKED ISSUE #4477: PODS 2.7RC1 Roles component goes in loop when save
schermata 2017-09-22 alle 09 46 33

### PR DESCRIPTION
**Pull request by pglewis**
Fixes #4477

### CODE REVIEW

**Comment by pglewis** [comment]
> Hmm how is data strictly an object and strictly null?

It's if `data` is an object but NOT null: `if ( 'object' === typeof data && null !== data )` 

`data` is the result from parseJSON, `d` is the raw data.  In the case of a roles save the AJAX call returns either `true` or an empty string in `d` (can't recall which)... but in any case the result of running that through `parseJSON` will return `null`.  

That new section of code assumes a valid object from parseJSON signals DFV support for modal add/edit but due to legacy Javascript stuff `typeof null` is 'object' as well.

**Comment by sc0ttkclark** [comment]
Oh FFS JavaScript, leave it to them to make null an object

**Comment by pglewis** [comment]
It was a glaring mistake in early implementations... but the real prob is the usual suspect: back-compat.  Once it's in the wild...

**Comment by pglewis** [comment]
Also, still not as glaring as `typeof NaN` = number :)

**Pull request merged**
