### PR TITLE
unit testing: phpunit 4.7

### PR DESCRIPTION
**Pull request by Ramoonus**
latest stable is now 4.7
https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-4.7.0

### CODE REVIEW

**Comment by Ramoonus** [comment]
next month I`ll bring an PHPUnit 4.8 patch
no 5.0 since that will drop support of PHP 5.3-5.5

**Comment by sc0ttkclark** [comment]
Needs re-base on 2.x branch, also needs a release/3.0 PR

**Comment by Ramoonus** [comment]
doubles of #2987 #2988

**Comment by Ramoonus** [comment]
replaced by #3090

**Pull request closed without merging**
