### PR TITLE
scrutinizer: use phpcs standard wordpress

### PR DESCRIPTION
**Pull request by Ramoonus**

### CODE REVIEW

**Comment by Ramoonus** [comment]
followup: remove phpcs from composer

@sc0ttkclark your opinion on this

**Comment by Ramoonus** [comment]
i think this is why the first one fails #3170 / #3171 / #3172

**Comment by sc0ttkclark** [comment]
I lean on your experience, if we don't need / use phpcs, and use Scrutinizer for that, then we can remove.

**Comment by Ramoonus** [comment]
only reason to keep it is that people could run it locally

**Pull request merged**
