### PR TITLE
Don't interfere with getting locale from user meta

### LINKED ISSUE #4368: WP_User $locale errors with recursion
I get an error after creating things with pods sometimes, on localhost. 

Notice: Undefined property: WP_User::$locale in /app/public/wp-includes/l10n.php on line 103

[2:41] 
 ```13    0.1177    11186656    PodsMeta->get_user_meta( )    .../class-wp-hook.php:298
14    0.1177    11187056    PodsMeta->get_meta( )    .../PodsMeta.php:2229
15    0.1178    11185952    pods( )    .../PodsMeta.php:2682
16    0.1180    11274416    Pods->__construct( )    .../classes.php:21
17    0.1180    11274416    pods_api( )    .../Pods.php:214
18    0.1180    11274416    PodsAPI::init( )    .../classes.php:68
19    0.1180    11274608    PodsAPI->__construct( )    .../PodsAPI.php:88
20    0.1181    11274984    PodsAPI->load_pod( )    .../PodsAPI.php:121
21    0.1295    13175792    PodsForm::field_setup( )    .../PodsAPI.php:5662
22    0.1295    13175792    PodsForm::field_loader( )    .../PodsForm.php:744
23    0.1305    13182240    PodsField_Pick->__construct( )    .../PodsForm.php:1234
24    0.1305    13182240    __( )    .../pick.php:101
25    0.1305    13182240    translate( )    .../l10n.php:202
26    0.1305    13182240    get_translations_for_domain( )    .../l10n.php:122
27    0.1305    13182240    _load_textdomain_just_in_time( )    .../l10n.php:947
28    0.1305    13182240    _get_path_to_translation( )    .../l10n.php:849
29    0.1305    13182240    _get_path_to_translation_from_lang_dir( )    .../l10n.php:879
30    0.1305    13182240    get_user_locale( )    .../l10n.php:917
```

### PR DESCRIPTION
**Pull request by sc0ttkclark**
Fixes #4368

### CODE REVIEW

**Comment by JoryHogeveen** [comment]
Haven't got this error yet but changes look good

**Comment by sc0ttkclark** [comment]
It seems to happen on local sites more than anything else.

cc: @lougreenwood

**Comment by JoryHogeveen** [comment]
Maybe also add it to the protected meta keys so users can't add a field with that key?
Or is that done automatically?

**Comment by sc0ttkclark** [comment]
I'd have to check, but yeah we could add it there too but this just circumvents the chain of functions that have to get called to get there. Protected keys should be checked here too ultimately I'd bet

**Pull request merged**
