### PR TITLE
Fix current user can in 3.0

### PR DESCRIPTION
**Pull request by afragen**
current_user_can not yet defined and causes a PHP fatal for me locally. Moving the check inside the `admin_notices` hook fixes this.

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Code itself needs clean up, it wasn't my original implementation it was copied from some test code.

**Comment by afragen** [comment]
Does it cause PHP fatal for you?

**Comment by sc0ttkclark** [comment]
It only fatals when you don't have the CMB2 files existing, so it doesn't fatal for me.

**Comment by sc0ttkclark** [comment]
I'm going to rewrite the code though, it shouldn't be like that anyways

**Comment by sc0ttkclark** [comment]
(we can't use anonymous functions in Pods because we still support 5.2.x like WP does)

**Pull request closed without merging**
