### PR TITLE
Feature/3642 field tests

### PR DESCRIPTION
**Pull request by pglewis**
#3642

### CODE REVIEW

**Comment by jamesgol** [comment]
Definitely don't merge yet, still a work in progress

**Comment by pglewis** [comment]
Yeah, I skipped this one but merged the other one with fixed tests.  2.x already has the php tests moved so you'll want to update your branch.

**Comment by pglewis** [comment]
What's the story on this?  It's against 2.x but on the 2.7 milestone and hasn't moved in a while.

**Comment by pglewis** [comment]
I'm going to assume I was either confused or just mis-clicked when I set this to 2.7.

**Comment by sc0ttkclark** [comment]
Does this work? Is this how we want it to be?

**Comment by pglewis** [comment]
> Definitely don't merge yet, still a work in progress

Needs a 'hold' label until James circles back around

**Pull request closed without merging**
