### PR TITLE
New Link field with WP link modal

### PR DESCRIPTION
**Pull request by JoryHogeveen**
See: https://github.com/pods-framework/pods/issues/2655
New PR for 2.7 (old: https://github.com/pods-framework/pods/pull/3588)

Adds a link field type with options to add a link with a title and
target.
Validation similar to website field.

UI has the option to open the WordPress link modal to search for
existing content and autofill the fields for this field.

pods_field_display() will show a formatted link.

link field

link field-modal

### CODE REVIEW

**Comment by jimtrue** [comment]
No Reviews? Just merged into 2.7?

**Comment by sc0ttkclark** [comment]
I did look into the code prior to merge, are you seeing any issues?

**Comment by jimtrue** [comment]
it saves properly as I can see, but it doesn't display() properly, comment from #2655 

> Never actually tested this one, sorry. Output isn't correct in a Magic Tag (ie we should just be able to go {@link_field} and it do all the necessary wrapping, etc.

>this is what it outputs: `and _blank`

>I think because it's actually built as an array, it output it as a display() list, so url, text, and target. It should actually construct the link.

**Comment by JoryHogeveen** [comment]
The `display()` function returns a HTML formatted link. How was this used?

**Comment by jimtrue** [comment]
In the Magic Tag format in a Pods Template {@link_field} so yep, it should've returned the display as a formatted HTML link.

**Comment by jimtrue** [comment]
This is exactly what was in my Pods Template:

`<div>Link Test: [if link_test]{@link_test}[else]No Link[/if]</div>`

**Comment by JoryHogeveen** [comment]
@sc0ttkclark 
https://github.com/pods-framework/pods/blob/release/2.7/classes/fields/link.php#L185-L187
Maybe there is a problem similar to the date field you've fixed? Diplay handling could be called multiple times when the data is an array.

**Comment by sc0ttkclark** [comment]
Gotcha, yeah we'll need to fix that like we fixed the address field display. Check that branch

**Comment by JoryHogeveen** [comment]
Maybe create a separate PR with those commits? Not sure if that is possible?

**Comment by sc0ttkclark** [comment]
Created in #4233

**Pull request merged**
