### PR TITLE
Test against php 7.2 too

### PR DESCRIPTION
**Pull request by sc0ttkclark**

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
wp version = latest is failing for everything right now, unrelated to this 7.2 change specifically. Not sure what's up there yet, unit test file is missing or something.

**Comment by JoryHogeveen** [comment]
It's working again

**Comment by JoryHogeveen** [comment]
And erroring on the use of `count()`

**Comment by sc0ttkclark** [comment]
Looks good ✅

**Pull request merged**
