### PR TITLE
travis-ci: add php 7.2 to testmatrix

### PR DESCRIPTION
**Pull request by Ramoonus**

### CODE REVIEW

**Comment by Ramoonus** [comment]
sorry for the delay

**Comment by JoryHogeveen** [comment]
@sc0ttkclark  Close this in favor of the current changes or is there anything else in here that needs to be checked and possibly merges?

**Comment by Ramoonus** [comment]
@JoryHogeveen can we do this?

**Comment by JoryHogeveen** [comment]
@Ramoonus What do you mean?
7.2 is already in the current matrix: https://github.com/pods-framework/pods/blob/2.x/.travis.yml#L18-L19

**Comment by sc0ttkclark** [comment]
Resolved by #4811

**Pull request closed without merging**
