### PR TITLE
codeclimate array fix

### PR DESCRIPTION
**Pull request by Ramoonus**

### CODE REVIEW

**Comment by pglewis** [comment]
This is YAML, not JSON... I don't think there needs to be commas at all?

**Comment by Ramoonus** [comment]
in that case i have to remove the comma`s on every line

**Comment by Ramoonus** [comment]
changed

**Comment by pglewis** [comment]
Needs indentation as well.  Tabs not allowed, lets go with 2 spaces to match the stuff below it.

**Pull request merged**
