### PR TITLE
WP Gallery display options for image fields

### PR DESCRIPTION
**Pull request by JoryHogeveen**
See #3905

### CODE REVIEW

**Comment by jimtrue** [comment]
@JoryHogeveen @sc0ttkclark @pglewis Did this get merged into 2.7? Some of the fields additions are in there but the primary option for 'Output this as a WP Gallery' isn't in the 2.7 branch I'm testing on.

**Comment by jimtrue** [comment]
Further comment, I'm getting 'erroneous' issues on one where it's available as an option AFTER adding the new field, but on a pod where the field already existed and was set for Gallery, the options aren't available. It's also doing some weirdness with Auto Templates. I'm going to do a new test on these both with creating brand new, and with taking existing and shifting them over (and yes, I've cleared cache).

**Comment by sc0ttkclark** [comment]
Can you test on latest 2.x stable to confirm the issues don't exist there too? Just so we can rule that out?

**Comment by sc0ttkclark** [comment]
I see the field options in 2.7 too

**Comment by jimtrue** [comment]
yeah I'm testing out a stable clean install. It was so weird it didn't make any sense.

**Comment by jimtrue** [comment]
But 3 different versions:

2.x with fields created and configured and then switching to 2.7
2.7 new addition in 2.7 only
2.x upgrading to 2.7 and switching back to 2.x (same as 1, but making sure that if they were created and upgraded, they still work correctly in 2.x)

**Comment by jimtrue** [comment]
I'm not seeing the oddness where the field wasn't available for selection, but what is happening is the Auto Templates aren't selectable (or it's not saving the selection, only defaulting to the first template in the list) upon saving and that's what was causing the issue I was seeing.

**Comment by JoryHogeveen** [comment]
So it's an auto template issue instead of WP Gallery options? Maybe it has something to do with the new DFV structure?

**Comment by jimtrue** [comment]
Let's keep discussion of this over in #4143 I noticed it because my pods had fields and relationships and were using the gallery feature, but it's definitely an Auto Template issue

**Pull request merged**
