### PR TITLE
Use proper tests checkout for WP_VERSION=latest

### PR DESCRIPTION
**Pull request by danielbachhuber**
This also removes some customizations you've made to the installation script, so you may not want to merge as-is.

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Needs further tweaks to merge into 2.x branch, as we have some customizations to install-wp-tests.sh to allow for 'trunk' as an option, versus latest stable.

**Comment by danielbachhuber** [comment]
> as we have some customizations to install-wp-tests.sh to allow for 'trunk' as an option, versus latest stable.

This would be nice to get upstream https://github.com/wp-cli/wp-cli/issues/1860

**Comment by Ramoonus** [comment]
Looking into it

**Comment by sc0ttkclark** [comment]
The one we were working with to test our Term meta code and our own tests against was this:

https://github.com/pods-framework/pods/blob/feature/3163-support-term-meta/bin/install-wp-tests.sh

**Comment by sc0ttkclark** [comment]
Looks like we've got this manually merged with what we have for bleeding/bleeding-maintenance, will follow up when we improve the install-wp-tests.sh as right now it's still somewhat limited and 'unclean' for pushing it upstream.

**Pull request closed without merging**
