### PR TITLE
Verify current filter before applying auto templates

### LINKED ISSUE #4695: Pods displaying after the_content, even when auto-template is set elsewhere
Description of issue:
--
I am using a Pods auto-template to display wholesale information after the woocommerce_short_description (the excerpt) shown here: 
However, even with the auto-template set to display after the woocommerce_short_description, it still ALSO shows after Description (the_content): 

Template settings: https://i.imgur.com/fhMHq16.png
I have also tried checking the "Execute outside the WP Loop" box, but it doesn't help.

Expected Result
--
I'd like to have the pod display only after the short description, not after the main description.

Functional Example:
--
Product: https://bbtooinc.com/product/green-bead-garden

You will need to be logged in as a Wholesale User. Use this login info:
LOGIN: https://bbtooinc.com/wholesale-log-in-page
USER: adam@gearboxstudios.com
PASS: UYx6ve9#eReOOsNWdn0FX6So

If it helps troubleshoot, I can also make you a temporary Admin user on this site. Let me know at joe@stoysnet.com if you need admin access.

### PR DESCRIPTION
**Pull request by JoryHogeveen**
Fixes #4695

### CODE REVIEW

**Comment by JoryHogeveen** [comment]
@jamesgol 
https://github.com/pods-framework/pods/blob/feature/4695-fix-autotemplate-hook-validation/components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php#L369

Is that line supposed to be there?

**Comment by JoryHogeveen** [comment]
Sorry, Git Blame points me to @Shelob9 !
See above comment :)

**Comment by jamesgol** [comment]
Yeah that is supposed to be there in an attempt to stop recursion.  The filter gets removed and then re-added.

**Comment by JoryHogeveen** [comment]
@jamesgol 
I removed it in this PR since this is what causes the loop as mentioned in the issue. Once the filter is set to a filter before `the_content` is called it shows on both `the_content` and the set filter.

What kind of loop did you mean?

**Comment by JoryHogeveen** [comment]
Ah wait, I think I get it. A Pods Template itself also triggers `the_content`?

**Comment by jamesgol** [comment]
Yeah there are a couple of obscure places that could happen, or at least it used to.  Not sure if anything else has changed since then.

**Comment by JoryHogeveen** [comment]
Ok clear then, reverted the commit. Should be good now, thanks!

**Comment by JoryHogeveen** [comment]
@sc0ttkclark Can this one be merged and closed?

**Comment by jimtrue** [comment]
ChangeLog:
* Fixed: Autotemplate hook validation to verify filter before applying Auto Templates (#4695) (@JoryHogeveen)

**Pull request merged**
