### PR TITLE
Feature/4612 prefix css various

### PR DESCRIPTION
**Pull request by nicdford**
Fixes specificity issues revealed with relation to #4612

### CODE REVIEW

**Comment by nicdford** [comment]
The only set of styles I wasn't able to test was 4bb2877 because I can't trackdown the timepicker html this is being applied to, but I wrapped it in the same `form.pods-form`, so hopefully that does the trick.

**Comment by nicdford** [comment]
26c9c19 fixes #4624 

Similar to the timepicker, I couldn't find where these advanced.scss styles are getting applied? I tried to track it down, but without luck. I'd rather remove them to fix this and have another issue popup and fix it properly with specificity, but since I don't know where these's helpers are getting used, it's hard to come up with a perfect fix.

**Comment by sc0ttkclark** [comment]
@nicdford please remove the wrap within the lib files, let's wrap them around the `@import` instead.

**Comment by nicdford** [comment]
@sc0ttkclark I really don't think we should use @import to wrap the tags, it's better if we can actually prefix each css line ie `.pods-codemirror`. This fix doesn't address that goal specifically, but I see it as a short-term fix as we start rebuilding more of the CSS to follow a better/more consistent prefixing standard. The goal of the pods.scss file is to keep it as an index of all the imports and not as a place for any actual styles so we can easily see what is getting imported and what isn't.

**Comment by pglewis** [comment]
Immediate use for the new 'Team Discussion' label :)

We should work out a solid plan moving forward after 2.7.1 goes out.  Some points to consider in both directions.

**Comment by JoryHogeveen** [comment]
I'm also not for wrapping around `@import` since it's not very dev friendly imo.

**Comment by pglewis** [comment]
> The goal of the pods.scss file is to keep it as an index of all the imports and not as a place for any actual styles so we can easily see what is getting imported and what isn't.

This definitely makes a lot of sense from a high level, organizational perspective.  

The opposite side is that wrapping the imports with our prefixes is a convenient DRY way to have a single point to change if those prefixes change, vs. search replace as well as a quick way to wrap generic styles sections like the jquery-ui stuff without having to go hacking up the whole stylesheet.

**Comment by nicdford** [comment]
Would it make sense to abstract third party code bases to make them more modular? Something like creating a new partial in libs that we have the @import wraps there? so like:
```
_jquery-qtip.scss
_jquery-ui-custom.scss
_libraries.scss
```
Then in `pods.scss` we'd just import `libs/libraries`? This would maintain the structure of `pods.scss`, allow us to then do the @import for the external libraries, and also theoretically would enable us to update libraries without having to re-prefix everything?

I think this makes sense for external libraries/overrides. I think for base styles it would make sense to base them on the html structure created for the module, like with dfv everything is prefixed with `pods-dfv-list`.

**Comment by sc0ttkclark** [comment]
theoretically, we'd want to wrap all libraries and qtip/jquery-ui stuff. So _libraries.scss would contain that too.

**Comment by nicdford** [comment]
> single point to change if those prefixes change, vs. search replace
Also, @pglewis, for base styles that pods is creating (like dfv) we can do some cool stuff with [storing prefixes in variables](http://www.scottohara.me/article/sass-selector-variables.html) with sass which might also be useful.

**Comment by nicdford** [comment]
> theoretically, we'd want to wrap all libraries and qtip/jquery-ui stuff. So _libraries.scss would contain that too.

Yeah, totally!

**Comment by pglewis** [comment]
> I'm also not for wrapping around @import since it's not very dev friendly imo.

I'd like to understand the downside(s) to this approach to see if we can come up with the "best of all worlds".  

The downsides of wrapping the entire file contents for me, like we're currently doing:

*  Interrupts the git blame history, as every line in the file is seen to be changed by Nic in this commit: https://github.com/pods-framework/pods/blame/26c9c19/ui/styles/src/libs/_jquery-qtip.scss
* Creates an extra nesting level around all 300 lines, when possible I really really prefer to see the full nesting structure for something in one screenful
* Introduces changes to a lot more files than wrapping the imports that need it
* Distributes the placement of prefixes among more files which can lead to more complicated search/replace in the future

The way I've been viewing our 3 main style files:
* pods: all the admin css
* pods-form: smaller subset for use with Pods Form on the front-end
* pods-wizard: made into its own bundle since we only need it in a few places and cuts the main file size

With that in mind, the three "main" .scss files basically represent the "build instructions" for their compiled counter-parts and it kinda feels to me like the right, DIY place to be wrapping our generic includes with name-spacing specifiers.  

I'm not sure another layer of partials with multiple libraries in it is a better choice, that makes the import of /it/ all or nothing.  Seems a lot of hoops to jump through just to avoid wrapping anything in the main file, but there may be good arguments for doing that, that I just don't see yet.

**Comment by pglewis** [comment]
Changelog: add appropriate namespace prefixes to avoid style conflicts (#4612)

**Pull request merged**
