### PR TITLE
Update polylang compatibility

### PR DESCRIPTION
**Pull request by JoryHogeveen**
Use $polylang->model to get the current language (since Polylang v1.2) if available.

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Double check our other usage of $polylang, this might not be the only place in the plugin. But this looks like a great fix!

Let me know if you find any others and want to include those fixes in this PR.

**Comment by sc0ttkclark** [comment]
I see no other areas with similar usage of $polylang (other uses of $polylang but not these types of calls). Merged and ready for Pods 2.5.6 release this month.

**Comment by JoryHogeveen** [comment]
Hi Scott, Sorry for my late reply but great to see this is ready for the next update. Thanks!

**Comment by JoryHogeveen** [comment]
Hi Scott,

Found this on the Polylang website:
https://polylang.wordpress.com/2015/11/24/polylang-1-8-for-the-developpers/

I think there will be new changes needed again.

**Comment by sc0ttkclark** [comment]
Sounds like you're about to get some more Pods props then :)

**Comment by JoryHogeveen** [comment]
Haha hint received ;) I will try to make some time a.s.a.p.!

**Pull request merged**
