### PR TITLE
Feature/7161 add new pod screen UI enhancement

### PR DESCRIPTION
**Pull request by heybran**
## Description

Improve layout on add new pod screen UI (including nice focus indicator).

## Related GitHub issue(s)

Enhancement #7161

## Screenshots / screencast

Screenshot 2023-12-09 at 23 22 41

https://github.com/pods-framework/pods/assets/75633537/317102b7-4d9c-4280-bb3a-eb2ca926758e

## Changelog text for these changes

Enhancement: Improve add new pod screen UI and tab support. #7161 (@heybran)

## PR checklist

- [x] I have tested my own code to confirm it works as I intended.
- [x] My code follows the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] My code follows the [WordPress Inline Documentation Standards](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/).
- [ ] My code includes automated tests for PHP and/or JS (if applicable).

### CODE REVIEW

**Comment by heybran** [comment]
The css is getting out of control Scott, maybe I should send a PR another time to better organise them.

**Comment by heybran** [comment]
@sc0ttkclark Hey Scott, wondering should I handle this `ui/styles/dist/pods-wizard.css` conflict?

**Comment by sc0ttkclark** [comment]
Don't worry about .css conflicts, just override and the auto-build step in CI will rebuild the dist .js/.css assets on that side.

**Comment by sc0ttkclark** [comment]
I pushed some more updates to your branch and dealt with some merge conflicts. I have to finish hooking up your changes alongside the quick action JS so it shows the right message once you click them. I'll work on that tomorrow.

**Comment by sc0ttkclark** [comment]
Updated UI to the following:

Screenshot 2024-09-09 at 11 13 30 PM
Screenshot 2024-09-09 at 11 13 58 PM

**Comment by sc0ttkclark** [comment]
Pre 3.2.8:

Screenshot 2024-09-09 at 2 43 05 PM

**Pull request merged**
