### PR TITLE
Update save_post / save_user handling with better fallbacks when nonce not active

### LINKED ISSUE #3801: pods_api_post_save_pod_item_{podname} and pods_api_post_save_pod_item
Both these functions does not set the $is_new_item as expected... i have tried elevated the priority to 1 when doing the add_action but no luck so far.

example code.
`add_action('pods_api_post_save_pod_item_monkey', 'nh_pod_post_save_item_monkey', 1, 3);
function nh_pod_post_save_item_monkey($pieces, $is_new_item, $id ) {
    if ($is_new_item)
    {
        die('its new monkey!');
    } else {
        die('No new monkey');
    }
}`

This will always return with no new monkey :(

### LINKED ISSUE #3918: When User is extended by Pods, saving a new user does not trigger 'pods_api_post_save_pod_item'
If User is extended by Pods and an action hook exists to do some stuff to new users, the hook is not triggered when new users are created.

However, hook is triggered upon first save of a user's profile.

### PR DESCRIPTION
**Pull request by sc0ttkclark**
Fixes #3801

Fixes #3918

### CODE REVIEW

**Comment by lougreenwood** [comment]
When updating 2.6.7 with the 2 modified files in this PR, I get an error when updating/saving a record:

```
Unhandled Exception

Message:

Undefined index: my_pod
Location:

/usr/share/nginx/html/htdocs/content/plugins/pods/classes/PodsMeta.php on line 1137
Stack Trace:

#0 /usr/share/nginx/html/htdocs/content/mu-plugins/themosis-framework/bootstrap/start.php(175): Themosis\Error\Error::native(8, 'Undefined index...', '/usr/share/ngin...', 1137)
#1 /usr/share/nginx/html/htdocs/content/plugins/pods/classes/PodsMeta.php(1137): THFWK_Themosis->{closure}(8, 'Undefined index...', '/usr/share/ngin...', 1137, Array)
#2 /usr/share/nginx/html/htdocs/admin/wp-includes/class-wp-hook.php(300): PodsMeta->save_post(170536, Object(WP_Post))
#3 /usr/share/nginx/html/htdocs/admin/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array)
#4 /usr/share/nginx/html/htdocs/admin/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#5 /usr/share/nginx/html/htdocs/admin/wp-includes/post.php(3505): do_action('save_post', 170536, Object(WP_Post), true)
#6 /usr/share/nginx/html/htdocs/admin/wp-includes/post.php(3578): wp_insert_post(Array, false)
#7 /usr/share/nginx/html/htdocs/admin/wp-admin/includes/post.php(378): wp_update_post(Array)
#8 /usr/share/nginx/html/htdocs/admin/wp-admin/post.php(193): edit_post()
#9 {main}
```

**Comment by sc0ttkclark** [comment]
@lougreenwood try the latest 2.x, this PR had to be merged first in order for #3937 to work properly.

**Comment by lougreenwood** [comment]
@sc0ttkclark Still get it. BTW - I'm using a copy of 2.x branch downloaded from GitHub web interface...

**Comment by sc0ttkclark** [comment]
Fixed the notice in #3941

**Pull request merged**
