### PR TITLE
Enhance currency field UI

### LINKED ISSUE #4713: Enhance currency field UI
Currently the currency field shows exactly the same as a number field. It could be nice to enhance the field UI with the currency signs etc.

Example:
image

## Related PR
#4714

## Todos
- [x] CSS compile
- [x] Tests
- [ ] Changelog

### PR DESCRIPTION
**Pull request by JoryHogeveen**
Fixes #4713

### CODE REVIEW

**Comment by JoryHogeveen** [comment]
I did not commit the compiled CSS files since this does not seem to compile the same as Pods currently has. Will check this further.

**Comment by sc0ttkclark** [comment]
Needs CSS rebuild via Grunt I believe? Also needs conflict resolution (sorry, phpcs stuff)

**Comment by JoryHogeveen** [comment]
@sc0ttkclark I've reverted the PHPCS changes due to the conflict. The code that was build (JS and PHP combined) wasn't readable at all. We might need to re-think code styling for JS blocks within PHP files.

**Comment by pglewis** [comment]
I have a minor display issue with the rebuilt CSS (inbound commit on the way): 

currency-ui
currency-ui-zoom

**Comment by JoryHogeveen** [comment]
@pglewis Could you check again?

**Comment by pglewis** [comment]
Yeah, I'm about to start this week's cyclone.  

Looks like you're able to build CSS now?

**Comment by JoryHogeveen** [comment]
Okidoki!
<shame>I manually modified the compiled file</shame>

**Comment by pglewis** [comment]
Fixed, and that display issue was all I found.  Good to merge as soon as tests clear.

**Comment by JoryHogeveen** [comment]
**Changelog**
Currency field enhancement: Add a currency sign before the field input.

**Pull request merged**
