### PR TITLE
PHPUnit 5 update (from 4)

### PR DESCRIPTION
**Pull request by Ramoonus**

### CODE REVIEW

**Comment by Ramoonus** [comment]
only fails on php 5.3
as expected; https://travis-ci.org/pods-framework/pods/jobs/198755607

**Comment by pglewis** [comment]
This is another one we can certainly include in 2.7 if it gets done, but I'm now reserving open 2.7 milestones for "must have" issues.

**Comment by Ramoonus** [comment]
roger that

**Comment by JoryHogeveen** [comment]
Are you sure you want to drop the PHP 5.3 tests? WP (sadly) still supports it...

**Comment by Ramoonus** [comment]
just keep it on hold for now

**Comment by sc0ttkclark** [comment]
Let's close this in favor of #3989 and the multi-phpunit version trick

**Pull request closed without merging**
