### PR TITLE
Fix for symlinkd pods in local dev environment

### PR DESCRIPTION
**Pull request by afragen**
See #2945

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Looks good, can you do a PR for `release/3.0` as well?

**Comment by afragen** [comment]
Sure, will do.

**Comment by afragen** [comment]
`release/3.0` PR #2947

**Comment by pglewis** [comment]
This change defeats the enforcement of the view being within the plugin directory of the install or within the theme.  I think we need to fix this at the source: making sure `PODS_DIR` points to wp-content/plugins/... and not the path of the symlink.

**Comment by afragen** [comment]
Really all this does is uncouple an `if elseif else` into some good simpler. I found the `elseif` wasn't working when $view had a valid file path. No idea why it wasn't but it wasn't.

**Comment by pglewis** [comment]
The initial `if` is hit here because the the path of the view is outside `WP_PLUGIN_DIR` and `WPMU_PLUGIN_DIR`, thus why the `elseif`doesn't get hit.  

`$located` is returning `false` from that initial `if` because the view's path is also determined to be outside `get_stylesheet_directory()` and `get_template_directory()`.  

The change defeats this enforcement of acceptable locations for the view and would allow a view in any location the server can read.

**Comment by pglewis** [comment]
There should be comments to make it clear what's happening there, but it's ultimately whitelisting acceptable locations.

**Comment by sc0ttkclark** [comment]
We should update the code here in 2.x and release/3.0 to reflect as @pglewis is suggesting. We should then allow either a filter (array) to add additional whitelisted locations, or a constant/filter (boolean) or something allowing outside locations.

**Comment by pglewis** [comment]
I'm shifting convo for the solution over to #2945

**Comment by pglewis** [comment]
An additional whitelist for views might be a good feature as well, but I think that's a separate feature request from this.  I *think* there should be a workable solution to figure out if the pod directory is a symlink and not dereference it when setting `PODS_DIR` if so.

**Comment by pglewis** [comment]
I'd like to suggest reverting this as it could be a potential security risk.  I'd also like to submit a separate pull request that makes the logic there a little more clear in the future.

**Comment by afragen** [comment]
The following is the logic, isn't it.

```php
$located = false;
 
 		if ( false === strpos( $_real_view, realpath( WP_PLUGIN_DIR ) ) && false === strpos( $_real_view, realpath( WPMU_PLUGIN_DIR ) ) ) {
 			$_real_view = trim( $_real_view, '/' );
 
 			if ( empty( $_real_view ) ) {
 				return false;
 			}
```
Code makes it here with file path.
```php 
 			if ( file_exists( realpath( get_stylesheet_directory() . '/' . $_real_view ) ) ) {
 				$located = realpath( get_stylesheet_directory() . '/' . $_real_view );
 			}
 			elseif ( file_exists( realpath( get_template_directory() . '/' . $_real_view ) ) ) {
 				$located = realpath( get_template_directory() . '/' . $_real_view );
 			}
```
It skips through that last if elseif because it's not in the proper path and should then get the next elseif. since the next elseif only checks to see that the file exists it shouldn't miss this.
```php
 		}
		// Allow includes within plugins directory too for plugins utilizing this
		elseif ( file_exists( $_view ) ) {
			$located = $_view;
		}
		else {
			$located = apply_filters( 'pods_view_locate_template', $located, $_view );
 		}
 
 		return $located;
```

As an abstract

```php
if ( false === strpos( $_real_view, realpath( WP_PLUGIN_DIR ) ) && false === strpos( $_real_view, realpath( WPMU_PLUGIN_DIR ) ) ) {

} else if ( file_exists() ) {

} else {

}

```
As the file exists it should match the `else if`

Please let me know where I'm wrong here.

**Comment by afragen** [comment]
I think it's really just the fact that I'm using it as a symlink locally that uncovered this. As `$located = false` immediately prior to this block the check in the patch keeps the logic consistent.

**Comment by pglewis** [comment]
The view's file can exist but not be *allowed*.  Allowable locations are somewhere in the plugin directory tree or your theme directory.  Because of the symlink dereferencing you are ending up with a file path in an unallowable location.  The logic change would allow a view in any location the server can read.  While it solves your particular issue it opens up a potential security hole by allowing views to be anywhere.

**Comment by sc0ttkclark** [comment]
Maybe we need one more `&&` in that non plugins/mu-plugins check to see if it's also not PODS_DIR, that should suffice here.

**Comment by pglewis** [comment]
Really, that may be all it needs: 

`if ( false === strpos( $_real_view, realpath( WP_PLUGIN_DIR ) ) && false === strpos( $_real_view, realpath( WPMU_PLUGIN_DIR ) ) && false === strpos( $_real_view, PODS_DIR ) )`

To whitelist whatever PODS_DIR is

**Pull request merged**
