### PR TITLE
update select2 to version 3.5.4

### PR DESCRIPTION
**Pull request by Ramoonus**
#3195

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
@Lindsayanng what's left?

**Comment by Lindsayanng** [comment]
@sc0ttkclark Just need a few people to test a few different scenarios.

**Comment by pglewis** [comment]
Is this superseded by #2592?

**Comment by pglewis** [comment]
I saw some hiccups testing that version during #3344 and opted to just bump us up one version for now.  #2592 has a clear path carved out for it.

**Pull request closed without merging**
