### PR TITLE
travis-ci: unit test php 7

### PR DESCRIPTION
**Pull request by Ramoonus**

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
Should we follow what bbPress did by using `nightly` instead and also adding it to allowed failures?

https://bbpress.trac.wordpress.org/changeset/5619

**Comment by Ramoonus** [comment]
I agree
since PHP 7 is not a final version but a nightly

**Comment by sc0ttkclark** [comment]
I'll leave that change to you, then I'll merge.

**Comment by sc0ttkclark** [comment]
Please recreate patch based on 2.x branch instead please.

**Pull request closed without merging**
