### PR TITLE
Polylang fixes and cleanup

### LINKED ISSUE #3572: WPML and Relationship Field issues - Not copying relationships with new translations
WPML and Relationship Field issues - Not copying relationships with new translations submitted via Slack by jimtrue

### PR DESCRIPTION
**Pull request by sc0ttkclark**
Fixes #3572 and #3506 

#### Editing content

- [ ] Relationships show the proper posts (Relationship field: Post type) for the current language of the post or term being edited
- [ ] Relationships show the proper terms (Relationship field: Taxonomy) for the current language of the post or term being edited

#### Displaying content

`[pods]` shortcodes, Pods() objects, and get_post_meta instances should work properly.

- [ ] Proper posts shown (Pod type: Post type) with shortcode or Pods::find() for the current selected language of the site
- [ ] Proper terms shown (Pod type: Taxonomy) with shortcode or Pods::find() for the current selected language of the site
- [ ] Relationships show the proper posts (Relationship field: Post type) for the current language of the post or term being displayed
- [ ] Relationships show the proper terms (Relationship field: Taxonomy) for the current language of the post or term being displayed

### CODE REVIEW

**Comment by JoryHogeveen** [comment]
Tests to do for Polylang and WPML:
All tests to be done with **one-way relationships** and **two-way** for both taxonomies and post_types:

**translated object <> translated object**
This should only return related objects with the same language

**translated object <> not-translated object**
This should return all available objects regardless of language

**translated object <> not-translated object**
This should return results as if Polylang or WPML was disabled

I've tested the above and all looks good to me exept for one bug:

When a object was previously enabled for translation there is a translation reference stored in the database. In order to fix this we need to check if the current object type is enabled for translation.

**Comment by JoryHogeveen** [comment]
Patch 0d9d73a fixed the bug above.

It also enables setting the preferred languages of a non-translateable object so the user can filter the content to relate to (similar function to menu's with Polylang).

**Comment by JoryHogeveen** [comment]
@sc0ttkclark 
> [pods] shortcodes, Pods() objects, and get_post_meta instances should work properly.

I think you are talking about the front-end of a website:

get_post_meta doesn't filter by language I believe (I actually never knew it did).
What if a user wants to display content of an other language? If Pods manually filters all content from post meta values this is not possible.

**Comment by sc0ttkclark** [comment]
We're not filtering post meta by language, just had a note to test and confirm things are working properly everywhere Pods::find() / shortcode loops are being used

**Comment by JoryHogeveen** [comment]
Did some front-end testing aswell (just to be sure) and no problems found.
Do note that I am not familiar with using the pods shortcodes and object. I all about the get_post_meta :)

**Comment by sc0ttkclark** [comment]
I've got a copy of the latest WPML for anyone who wishes to test.

**Comment by JoryHogeveen** [comment]
Sure! I can do some tests like I did with Polylang

**Comment by sc0ttkclark** [comment]
Looks good to me!

**Comment by JoryHogeveen** [comment]
Related: https://github.com/pods-framework/pods/issues/2369

**Pull request merged**
