### PR TITLE
Don't let Pods overwrite admin menu items

### LINKED ISSUE #2673: Too many Pods will overwrite admin menu
Using add_object_page doesn't check the count of items in the admin menu so it can overwrite.  I noticed that my plugins and themes menus disappeared when I had a lot of Pods on my test setup.

PR incoming

### PR DESCRIPTION
**Pull request by jamesgol**
Fixed #2673

### CODE REVIEW

**Comment by sc0ttkclark** [comment]
I'm not 100% sure yet on this, since if a object doesn't have a menu position set, it will go to the bottom of the menu items, instead of the bottom of the object menu group. Moving all current Pods for people who may be used to finding them where they're at now. Does it sound better if we just internally track menu position via a local incremental variable, if empty, just increment and use a decimal to avoid conflicts.

So 3 menus:

* 6.001
* 6.002
* 6.003

**Comment by jamesgol** [comment]
On my test setup (with about 65 pods that are a mix of everything) it doesn't really change the order except not overwriting anything.  I think one of them has a position explicitly set but the rest are default.  The groupings are the same.  CPT's up top below "Comments".  ACT start after "Settings" and go up to "Pods Admin"

**Comment by sc0ttkclark** [comment]
Line 207 has the $menu_position null bit, so you can take out the others.

I'm still wondering why add_menu_page is performing like that, when it's null it appends to the end:

```php
$new_menu = array( $menu_title, $capability, $menu_slug, $page_title, 'menu-top ' . $icon_class . $hookname, $hookname, $icon_url );

	if ( null === $position )
		$menu[] = $new_menu;
	else
		$menu[$position] = $new_menu;
```

**Comment by sc0ttkclark** [comment]
Let's get one more person doing a test on this with lots of Pods to be sure.

**Comment by Shelob9** [comment]
I tested and this works as expected. Merging.

**Pull request merged**
